Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2019-11, with the labels that each got.

#229 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request_direction/i18n/es.po
  stock_request_submit/i18n/es.po
Labels: 12.0

#230 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request_direction/i18n/es.po
  stock_request_submit/i18n/es.po
Labels: 12.0

#225 [bt#8874] fixes company_id of locations
  partner_location_auto_create/__manifest__.py
  partner_location_auto_create/migrations/11.0.1.0.1/pre-migration.py
  partner_location_auto_create/models/res_partner.py
Labels: 11.0-xp

#232 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_inventory_exclude_sublocation/__manifest__.py
  stock_inventory_exclude_sublocation/tests/test_exclude_sublocation.py
Labels: 12.0

#233 [bt#8847] fix locations company for subloacations of supplier/customer
  partner_location_auto_create/models/res_partner.py
  partner_location_auto_create/models/stock_location.py
  partner_location_auto_create/views/stock_location_view.xml
Labels: 11.0-xp

#235 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  .travis.yml
Labels: 9.0

#236 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_move_location/odoo/addons/stock_move_location
  setup/stock_move_location/setup.py
  stock_move_location/README.rst
  stock_move_location/__init__.py
  stock_move_location/__manifest__.py
  stock_move_location/data/stock_quant_view.xml
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/models/__init__.py
  stock_move_location/models/stock_move.py
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/readme/DESCRIPTION.rst
  stock_move_location/readme/ROADMAP.rst
  stock_move_location/readme/USAGE.rst
  stock_move_location/static/description/icon.png
  stock_move_location/static/description/index.html
  stock_move_location/tests/__init__.py
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/__init__.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: 12.0

#237 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/stock_move.py
Labels: 11.0

#238 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/stock_move.py
Labels: 12.0

#239 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_request_purchase/__manifest__.py
  stock_request_purchase/models/stock_request_order.py
Labels: 11.0

#240 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_cycle_count/tests/test_stock_cycle_count.py
Labels: 12.0

#241 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_request/__manifest__.py
  stock_request/static/description/icon.png
  stock_request/static/description/icon.svg
Labels: 11.0

#242 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request/__manifest__.py
  stock_request/static/description/icon.png
  stock_request/static/description/icon.svg
Labels: 12.0

#243 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  .editorconfig
Labels: 10.0

#244 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  .editorconfig
Labels: 11.0

#245 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  .editorconfig
Labels: 12.0

#246 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  .editorconfig
Labels: 13.0

#247 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request_purchase/__manifest__.py
  stock_request_purchase/models/stock_request_order.py
Labels: 12.0

#248 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_inventory_lockdown/i18n/pt_BR.po
  stock_inventory_preparation_filter/i18n/pt_BR.po
  stock_warehouse_orderpoint_stock_info/i18n/pt_BR.po
Labels: 12.0

#249 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available_unreserved/i18n/es.po
Labels: 12.0

#251 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/view/pull_rule.xml
Labels: 12.0

#252 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_request/__manifest__.py
  stock_request/models/stock_request_abstract.py
  stock_request/models/stock_request_order.py
Labels: 11.0
