Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2020-11, with the labels that each got.

#429 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 13.0

#430 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
Labels: 14.0

#431 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_lockdown/odoo/addons/stock_location_lockdown
  setup/stock_location_lockdown/setup.py
  stock_location_lockdown/README.rst
  stock_location_lockdown/__init__.py
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/i18n/es.po
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/pt.po
  stock_location_lockdown/i18n/stock_location_lockdown.pot
  stock_location_lockdown/i18n/zh_CN.po
  stock_location_lockdown/models/__init__.py
  stock_location_lockdown/models/stock_location.py
  stock_location_lockdown/models/stock_quant.py
  stock_location_lockdown/readme/CONTRIBUTORS.rst
  stock_location_lockdown/readme/DESCRIPTION.rst
  stock_location_lockdown/readme/USAGE.rst
  stock_location_lockdown/static/description/icon.png
  stock_location_lockdown/static/description/index.html
  stock_location_lockdown/tests/__init__.py
  stock_location_lockdown/tests/test_block_stock_location_entrance.py
  stock_location_lockdown/views/stock_location.xml
Labels: 13.0

#432 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/pt.po
  stock_location_lockdown/i18n/zh_CN.po
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/product.py
  stock_secondary_unit/views/product_views.xml
Labels: 13.0

#433 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  requirements.txt
  stock_location_limit_product/README.rst
  stock_location_limit_product/__manifest__.py
  stock_location_limit_product/static/description/index.html
Labels: 12.0

#434 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#437 Removing unneeded ext folder
  ext/.gitignore
Labels: 12.0.project_mi_465

#438 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_move_location/__manifest__.py
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: 13.0

#439 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available/i18n/fr.po
  stock_available_mrp/i18n/fr.po
  stock_available_unreserved/i18n/fr.po
Labels: 12.0

#440 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_mts_mto_rule/odoo/addons/stock_mts_mto_rule
  setup/stock_mts_mto_rule/setup.py
  stock_mts_mto_rule/README.rst
  stock_mts_mto_rule/__init__.py
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/data/stock_data.xml
  stock_mts_mto_rule/i18n/cs_CZ.po
  stock_mts_mto_rule/i18n/de.po
  stock_mts_mto_rule/i18n/es.po
  stock_mts_mto_rule/i18n/es_MX.po
  stock_mts_mto_rule/i18n/fr.po
  stock_mts_mto_rule/i18n/fr_FR.po
  stock_mts_mto_rule/i18n/hr.po
  stock_mts_mto_rule/i18n/it.po
  stock_mts_mto_rule/i18n/nl.po
  stock_mts_mto_rule/i18n/nl_NL.po
  stock_mts_mto_rule/i18n/pt_BR.po
  stock_mts_mto_rule/i18n/pt_PT.po
  stock_mts_mto_rule/i18n/ro.po
  stock_mts_mto_rule/i18n/sk.po
  stock_mts_mto_rule/i18n/sl.po
  stock_mts_mto_rule/i18n/stock_mts_mto_rule.pot
  stock_mts_mto_rule/i18n/tr_TR.po
  stock_mts_mto_rule/i18n/vi_VN.po
  stock_mts_mto_rule/i18n/zh_CN.po
  stock_mts_mto_rule/models/__init__.py
  stock_mts_mto_rule/models/stock_rule.py
  stock_mts_mto_rule/models/stock_warehouse.py
  stock_mts_mto_rule/static/description/icon.png
  stock_mts_mto_rule/tests/__init__.py
  stock_mts_mto_rule/tests/test_mto_mts_route.py
  stock_mts_mto_rule/view/pull_rule.xml
  stock_mts_mto_rule/view/warehouse.xml
Labels: 13.0

#441 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_request_picking_type/odoo/addons/stock_request_picking_type
  setup/stock_request_picking_type/setup.py
  stock_mts_mto_rule/i18n/cs_CZ.po
  stock_mts_mto_rule/i18n/de.po
  stock_mts_mto_rule/i18n/es.po
  stock_mts_mto_rule/i18n/es_MX.po
  stock_mts_mto_rule/i18n/fr.po
  stock_mts_mto_rule/i18n/fr_FR.po
  stock_mts_mto_rule/i18n/hr.po
  stock_mts_mto_rule/i18n/it.po
  stock_mts_mto_rule/i18n/nl.po
  stock_mts_mto_rule/i18n/nl_NL.po
  stock_mts_mto_rule/i18n/pt_BR.po
  stock_mts_mto_rule/i18n/pt_PT.po
  stock_mts_mto_rule/i18n/ro.po
  stock_mts_mto_rule/i18n/sk.po
  stock_mts_mto_rule/i18n/sl.po
  stock_mts_mto_rule/i18n/tr_TR.po
  stock_mts_mto_rule/i18n/vi_VN.po
  stock_mts_mto_rule/i18n/zh_CN.po
  stock_request_picking_type/README.rst
  stock_request_picking_type/__init__.py
  stock_request_picking_type/__manifest__.py
  stock_request_picking_type/data/stock_picking_type.xml
  stock_request_picking_type/i18n/es.po
  stock_request_picking_type/i18n/pt_BR.po
  stock_request_picking_type/i18n/stock_request_picking_type.pot
  stock_request_picking_type/i18n/zh_CN.po
  stock_request_picking_type/migrations/12.0.2.0.0/post-migration.py
  stock_request_picking_type/models/__init__.py
  stock_request_picking_type/models/stock_picking_type.py
  stock_request_picking_type/models/stock_request_order.py
  stock_request_picking_type/readme/CONTRIBUTORS.rst
  stock_request_picking_type/readme/DESCRIPTION.rst
  stock_request_picking_type/readme/USAGE.rst
  stock_request_picking_type/static/description/icon.png
  stock_request_picking_type/static/description/index.html
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_order_views.xml
Labels: 13.0

#443 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_request/i18n/de.po
  stock_request/i18n/es.po
  stock_request_tier_validation/i18n/es.po
Labels: 11.0

#444 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available_unreserved/i18n/ar.po
  stock_available_unreserved/i18n/de.po
  stock_available_unreserved/i18n/es.po
  stock_available_unreserved/i18n/pt_BR.po
  stock_available_unreserved/i18n/zh_CN.po
  stock_location_limit_product/i18n/es.po
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/pt.po
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_orderpoint_generator/i18n/es.po
  stock_request_purchase/i18n/de.po
  stock_request_tier_validation/i18n/es.po
Labels: 12.0

#445 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  procurement_auto_create_group/i18n/cs_CZ.po
  procurement_auto_create_group/i18n/de.po
  procurement_auto_create_group/i18n/es.po
  procurement_auto_create_group/i18n/hr.po
  procurement_auto_create_group/i18n/it.po
  procurement_auto_create_group/i18n/sl.po
  stock_available/i18n/ar.po
  stock_inventory_lockdown/i18n/cs_CZ.po
  stock_inventory_lockdown/i18n/pt_BR.po
  stock_inventory_lockdown/i18n/zh_CN.po
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/pt.po
  stock_quant_manual_assign/i18n/de.po
  stock_quant_manual_assign/i18n/es.po
  stock_quant_manual_assign/i18n/fi.po
  stock_quant_manual_assign/i18n/sl.po
  stock_request_picking_type/i18n/es.po
  stock_request_picking_type/i18n/pt_BR.po
  stock_request_picking_type/i18n/zh_CN.po
Labels: 13.0

#442 Update 20201124 - Updating from braintec fork
  stock_available/i18n/fr.po
  stock_available_mrp/i18n/fr.po
  stock_available_unreserved/i18n/ar.po
  stock_available_unreserved/i18n/de.po
  stock_available_unreserved/i18n/es.po
  stock_available_unreserved/i18n/fr.po
  stock_available_unreserved/i18n/pt_BR.po
  stock_available_unreserved/i18n/zh_CN.po
  stock_location_limit_product/i18n/es.po
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/pt.po
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_orderpoint_generator/i18n/es.po
  stock_request_purchase/i18n/de.po
  stock_request_tier_validation/i18n/es.po
Labels: 12.0.project_mi_465

#447 [t113973] Update 20201201: Sets commitortag for odoo and enterprise
  .braintec/deploy.yaml
Labels: 12.0.project_mi_465
