Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2020-10, with the labels that each got.

#407 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_inventory_cost_info/i18n/pt_BR.po
Labels: 11.0

#409 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_cycle_count/i18n/pt_BR.po
  stock_inventory_cost_info/i18n/pt_BR.po
Labels: 11.0

#410 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_orderpoint_purchase_link/i18n/fr.po
Labels: 12.0

#411 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_location_tray/__manifest__.py
  stock_location_tray/tests/test_location.py
Labels: 13.0

#412 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_production_lot_quantity_tree/odoo/addons/stock_production_lot_quantity_tree
  setup/stock_production_lot_quantity_tree/setup.py
  stock_production_lot_quantity_tree/README.rst
  stock_production_lot_quantity_tree/__init__.py
  stock_production_lot_quantity_tree/__manifest__.py
  stock_production_lot_quantity_tree/i18n/stock_production_lot_quantity_tree.pot
  stock_production_lot_quantity_tree/readme/CONTRIBUTORS.rst
  stock_production_lot_quantity_tree/readme/DESCRIPTION.rst
  stock_production_lot_quantity_tree/static/description/icon.png
  stock_production_lot_quantity_tree/static/description/index.html
  stock_production_lot_quantity_tree/views/stock_production_lot.xml
Labels: 12.0

#413 Update 20201020 - Updating from braintec fork
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_production_lot_quantity_tree/odoo/addons/stock_production_lot_quantity_tree
  setup/stock_production_lot_quantity_tree/setup.py
  stock_orderpoint_purchase_link/i18n/fr.po
  stock_production_lot_quantity_tree/README.rst
  stock_production_lot_quantity_tree/__init__.py
  stock_production_lot_quantity_tree/__manifest__.py
  stock_production_lot_quantity_tree/i18n/stock_production_lot_quantity_tree.pot
  stock_production_lot_quantity_tree/readme/CONTRIBUTORS.rst
  stock_production_lot_quantity_tree/readme/DESCRIPTION.rst
  stock_production_lot_quantity_tree/static/description/icon.png
  stock_production_lot_quantity_tree/static/description/index.html
  stock_production_lot_quantity_tree/views/stock_production_lot.xml
Labels: 12.0.project_mi_465

#414 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_request_direction/odoo/addons/stock_request_direction
  setup/stock_request_direction/setup.py
  setup/stock_request_submit/odoo/addons/stock_request_submit
  setup/stock_request_submit/setup.py
  stock_request/__manifest__.py
  stock_request/models/stock_request_abstract.py
  stock_request_direction/README.rst
  stock_request_direction/__init__.py
  stock_request_direction/__manifest__.py
  stock_request_direction/i18n/es.po
  stock_request_direction/i18n/stock_request_direction.pot
  stock_request_direction/i18n/zh_CN.po
  stock_request_direction/models/__init__.py
  stock_request_direction/models/stock_request.py
  stock_request_direction/models/stock_request_order.py
  stock_request_direction/readme/CONTRIBUTORS.rst
  stock_request_direction/readme/DESCRIPTION.rst
  stock_request_direction/readme/USAGE.rst
  stock_request_direction/static/description/icon.png
  stock_request_direction/static/description/index.html
  stock_request_direction/views/res_config_settings.xml
  stock_request_direction/views/stock_request_order_views.xml
  stock_request_direction/views/stock_request_views.xml
  stock_request_submit/README.rst
  stock_request_submit/__init__.py
  stock_request_submit/__manifest__.py
  stock_request_submit/i18n/es.po
  stock_request_submit/i18n/stock_request_submit.pot
  stock_request_submit/i18n/zh_CN.po
  stock_request_submit/models/__init__.py
  stock_request_submit/models/stock_request.py
  stock_request_submit/models/stock_request_order.py
  stock_request_submit/readme/CONTRIBUTORS.rst
  stock_request_submit/readme/DESCRIPTION.rst
  stock_request_submit/static/description/icon.png
  stock_request_submit/static/description/index.html
  stock_request_submit/tests/__init__.py
  stock_request_submit/tests/test_stock_request_submit.py
  stock_request_submit/uninstall_hook.py
  stock_request_submit/views/stock_request_order_views.xml
  stock_request_submit/views/stock_request_views.xml
Labels: 13.0

#415 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_orderpoint_manual_procurement_uom/odoo/addons/stock_orderpoint_manual_procurement_uom
  setup/stock_orderpoint_manual_procurement_uom/setup.py
  stock_orderpoint_manual_procurement_uom/README.rst
  stock_orderpoint_manual_procurement_uom/__init__.py
  stock_orderpoint_manual_procurement_uom/__manifest__.py
  stock_orderpoint_manual_procurement_uom/i18n/stock_orderpoint_manual_procurement_uom.pot
  stock_orderpoint_manual_procurement_uom/i18n/zh_CN.po
  stock_orderpoint_manual_procurement_uom/models/__init__.py
  stock_orderpoint_manual_procurement_uom/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement_uom/readme/CONTRIBUTORS.rst
  stock_orderpoint_manual_procurement_uom/readme/DESCRIPTION.rst
  stock_orderpoint_manual_procurement_uom/readme/USAGE.rst
  stock_orderpoint_manual_procurement_uom/static/description/icon.png
  stock_orderpoint_manual_procurement_uom/static/description/index.html
  stock_orderpoint_manual_procurement_uom/tests/__init__.py
  stock_orderpoint_manual_procurement_uom/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement_uom/wizards/__init__.py
  stock_orderpoint_manual_procurement_uom/wizards/make_procurement_orderpoint.py
Labels: 13.0

#418 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_pull_list/__manifest__.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
Labels: 12.0

#419 [t113973] Preparing stock-logistics-warehouse for brain-tec's Docker.
  .braintec/deploy.yaml
  ext/.gitignore
Labels: 12.0.project_mi_465

#420 [t113973] Preparing stock-logistics-warehouse for brain-tec's Docker.
  .braintec/deploy.yaml
Labels: 12.0.project_mi_465

#421 [t113973] Preparing stock-logistics-warehouse for brain-tec's Docker.
  .braintec/deploy.yaml
Labels: 12.0.project_mi_465

#422 [t113973] Preparing stock-logistics-warehouse for brain-tec's Docker.
  .braintec/deploy.yaml
Labels: 12.0.project_mi_465

#423 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#425 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_inventory_lockdown/__manifest__.py
  stock_inventory_lockdown/models/stock_location.py
Labels: 13.0

#426 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/models/vertical_lift_operation_put.py
Labels: 13.0

#428 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_inventory_line_open/odoo/addons/stock_inventory_line_open
  setup/stock_inventory_line_open/setup.py
  stock_inventory_line_open/README.rst
  stock_inventory_line_open/__init__.py
  stock_inventory_line_open/__manifest__.py
  stock_inventory_line_open/i18n/stock_inventory_line_open.pot
  stock_inventory_line_open/models/__init__.py
  stock_inventory_line_open/models/stock_inventory.py
  stock_inventory_line_open/readme/CONTRIBUTORS.rst
  stock_inventory_line_open/readme/DESCRIPTION.rst
  stock_inventory_line_open/static/description/icon.png
  stock_inventory_line_open/static/description/index.html
  stock_inventory_line_open/views/stock_inventory_view.xml
Labels: 13.0
