Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2020-09, with the labels that each got.

#396 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_inventory_cost_info/odoo/addons/stock_inventory_cost_info
  setup/stock_inventory_cost_info/setup.py
  stock_inventory_cost_info/README.rst
  stock_inventory_cost_info/__init__.py
  stock_inventory_cost_info/__manifest__.py
  stock_inventory_cost_info/hooks.py
  stock_inventory_cost_info/i18n/es.po
  stock_inventory_cost_info/i18n/stock_inventory_cost_info.pot
  stock_inventory_cost_info/models/__init__.py
  stock_inventory_cost_info/models/stock_inventory.py
  stock_inventory_cost_info/readme/CONTRIBUTORS.rst
  stock_inventory_cost_info/readme/DESCRIPTION.rst
  stock_inventory_cost_info/readme/INSTALL.rst
  stock_inventory_cost_info/readme/USAGE.rst
  stock_inventory_cost_info/static/description/icon.png
  stock_inventory_cost_info/static/description/index.html
  stock_inventory_cost_info/tests/__init__.py
  stock_inventory_cost_info/tests/test_stock_inventory_cost_info.py
  stock_inventory_cost_info/views/report_stockinventory.xml
  stock_inventory_cost_info/views/stock_inventory_views.xml
Labels: 13.0

#397 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_account_inventory_force_date/i18n/sl.po
  stock_available_unreserved/i18n/sl.po
  stock_mts_mto_rule/i18n/sl.po
  stock_request/i18n/sl.po
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/sl.po
Labels: 12.0

#398 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_inventory_cost_info/i18n/es.po
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/migrations/13.0.1.0.1/post-migration.py
  stock_secondary_unit/views/product_views.xml
Labels: 13.0

#400 Update 20200922 - Updating from braintec fork
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_putaway_product_form/odoo/addons/stock_putaway_product_form
  setup/stock_putaway_product_form/setup.py
  stock_account_inventory_force_date/i18n/sl.po
  stock_available_unreserved/i18n/sl.po
  stock_mts_mto_rule/i18n/sl.po
  stock_putaway_product_form/README.rst
  stock_putaway_product_form/__init__.py
  stock_putaway_product_form/__manifest__.py
  stock_putaway_product_form/demo/putaway_strategies.xml
  stock_putaway_product_form/hooks.py
  stock_putaway_product_form/i18n/stock_putaway_product_form.pot
  stock_putaway_product_form/models/__init__.py
  stock_putaway_product_form/models/product_product.py
  stock_putaway_product_form/models/product_template.py
  stock_putaway_product_form/models/putaway_strategy.py
  stock_putaway_product_form/readme/CONTRIBUTORS.rst
  stock_putaway_product_form/readme/DESCRIPTION.rst
  stock_putaway_product_form/readme/USAGE.rst
  stock_putaway_product_form/static/description/icon.png
  stock_putaway_product_form/static/description/index.html
  stock_putaway_product_form/tests/__init__.py
  stock_putaway_product_form/tests/test_product_putaway.py
  stock_putaway_product_form/views/product.xml
  stock_request/i18n/sl.po
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/sl.po
Labels: 12.0.project_mi_465

#402 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  product_quantity_update_force_inventory/README.rst
  product_quantity_update_force_inventory/__init__.py
  product_quantity_update_force_inventory/__manifest__.py
  product_quantity_update_force_inventory/i18n/product_quantity_update_force_inventory.pot
  product_quantity_update_force_inventory/models/__init__.py
  product_quantity_update_force_inventory/models/product.py
  product_quantity_update_force_inventory/models/stock_quant.py
  product_quantity_update_force_inventory/readme/CONTRIBUTORS.rst
  product_quantity_update_force_inventory/readme/DESCRIPTION.rst
  product_quantity_update_force_inventory/static/description/icon.png
  product_quantity_update_force_inventory/static/description/index.html
  product_quantity_update_force_inventory/tests/__init__.py
  product_quantity_update_force_inventory/tests/test_stock_quant_editable_view_block.py
  product_quantity_update_force_inventory/views/product_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_quantity_update_force_inventory/odoo/addons/product_quantity_update_force_inventory
  setup/product_quantity_update_force_inventory/setup.py
Labels: 13.0

#403 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_mts_mto_rule/i18n/fr.po
Labels: 12.0
