Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2020-12, with the labels that each got.

#449 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_move_location/odoo/addons/stock_move_location
  setup/stock_move_location/setup.py
  stock_move_location/README.rst
  stock_move_location/__init__.py
  stock_move_location/__manifest__.py
  stock_move_location/data/stock_quant_view.xml
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/init_hook.py
  stock_move_location/models/__init__.py
  stock_move_location/models/stock_move.py
  stock_move_location/models/stock_picking_type.py
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/readme/DESCRIPTION.rst
  stock_move_location/readme/ROADMAP.rst
  stock_move_location/readme/USAGE.rst
  stock_move_location/security/ir.model.access.csv
  stock_move_location/static/description/icon.png
  stock_move_location/static/description/index.html
  stock_move_location/tests/__init__.py
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/views/stock_picking_type_views.xml
  stock_move_location/wizard/__init__.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: 14.0

#450 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/models/stock_quant.py
Labels: 12.0

#451 Update 20201215 - Updating from latest OCA 12.0
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/models/stock_quant.py
Labels: 12.0.project_mi_465

#452 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  .travis.yml
Labels: 14.0

#453 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_putaway_product_form/__init__.py
  stock_putaway_product_form/__manifest__.py
Labels: 12.0

#454 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/i18n/stock_reserve_rule.pot
  stock_reserve_rule/migrations/13.0.1.1.0/post-migration.py
  stock_reserve_rule/models/__init__.py
  stock_reserve_rule/models/stock_picking_type.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
  stock_reserve_rule/views/stock_reserve_rule_views.xml
Labels: 13.0
