Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2020-07, with the labels that each got.

#352 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/tests/test_packaging_calc.py
Labels: 13.0

#353 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_move_location/i18n/sk_SK.po
Labels: 12.0

#354 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_location_tray/__manifest__.py
  stock_location_tray/models/stock_location.py
Labels: 13.0

#355 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  .travis.yml
  stock_inventory_preparation_filter/__manifest__.py
  stock_inventory_preparation_filter/models/stock_inventory.py
  stock_move_location/i18n/sk.po
Labels: 12.0

#356 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_pull_list/odoo/addons/stock_pull_list
  setup/stock_pull_list/setup.py
  stock_pull_list/README.rst
  stock_pull_list/__init__.py
  stock_pull_list/__manifest__.py
  stock_pull_list/i18n/stock_pull_list.pot
  stock_pull_list/readme/CONTRIBUTORS.rst
  stock_pull_list/readme/DESCRIPTION.rst
  stock_pull_list/readme/ROADMAP.rst
  stock_pull_list/readme/USAGE.rst
  stock_pull_list/static/description/icon.png
  stock_pull_list/static/description/index.html
  stock_pull_list/tests/__init__.py
  stock_pull_list/tests/common.py
  stock_pull_list/tests/test_stock_pull_list.py
  stock_pull_list/wizards/__init__.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
  stock_pull_list/wizards/stock_pull_list_wizard.xml
Labels: 12.0

#357 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_orderpoint_move_link/i18n/fr.po
  stock_orderpoint_mrp_link/i18n/fr.po
Labels: 12.0

#364 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_type_user_restriction/odoo/addons/stock_picking_type_user_restriction
  setup/stock_picking_type_user_restriction/setup.py
  stock_picking_type_user_restriction/README.rst
  stock_picking_type_user_restriction/__init__.py
  stock_picking_type_user_restriction/__manifest__.py
  stock_picking_type_user_restriction/i18n/it.po
  stock_picking_type_user_restriction/i18n/stock_picking_type_user_restriction.pot
  stock_picking_type_user_restriction/models/__init__.py
  stock_picking_type_user_restriction/models/stock_picking_type.py
  stock_picking_type_user_restriction/readme/CONFIGURE.rst
  stock_picking_type_user_restriction/readme/CONTRIBUTORS.rst
  stock_picking_type_user_restriction/readme/DESCRIPTION.rst
  stock_picking_type_user_restriction/security/ir.model.access.csv
  stock_picking_type_user_restriction/security/stock_security.xml
  stock_picking_type_user_restriction/static/description/icon.png
  stock_picking_type_user_restriction/static/description/index.html
  stock_picking_type_user_restriction/tests/__init__.py
  stock_picking_type_user_restriction/tests/test_picking_type_user_restriction.py
  stock_picking_type_user_restriction/views/product_views.xml
  stock_picking_type_user_restriction/views/stock_inventory_views.xml
  stock_picking_type_user_restriction/views/stock_menu_views.xml
  stock_picking_type_user_restriction/views/stock_picking_type_views.xml
  stock_picking_type_user_restriction/views/stock_picking_views.xml
  stock_picking_type_user_restriction/views/stock_warehouse_views.xml
Labels: 12.0

#368 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_cubiscan/__manifest__.py
  stock_cubiscan/i18n/stock_cubiscan.pot
  stock_cubiscan/models/stock.py
Labels: 13.0

#370 [t117924] Migration of stock_available_sale.
  stock_available_sale/README.rst
  stock_available_sale/__init__.py
  stock_available_sale/__manifest__.py
  stock_available_sale/i18n/ca.po
  stock_available_sale/i18n/cs_CZ.po
  stock_available_sale/i18n/de.po
  stock_available_sale/i18n/el_GR.po
  stock_available_sale/i18n/es.po
  stock_available_sale/i18n/es_ES.po
  stock_available_sale/i18n/es_MX.po
  stock_available_sale/i18n/eu.po
  stock_available_sale/i18n/fi.po
  stock_available_sale/i18n/fr.po
  stock_available_sale/i18n/fr_CH.po
  stock_available_sale/i18n/fr_FR.po
  stock_available_sale/i18n/gl.po
  stock_available_sale/i18n/hr.po
  stock_available_sale/i18n/hr_HR.po
  stock_available_sale/i18n/it.po
  stock_available_sale/i18n/nl.po
  stock_available_sale/i18n/nl_NL.po
  stock_available_sale/i18n/pt.po
  stock_available_sale/i18n/pt_BR.po
  stock_available_sale/i18n/ro.po
  stock_available_sale/i18n/ru.po
  stock_available_sale/i18n/sl.po
  stock_available_sale/i18n/stock_available_sale.pot
  stock_available_sale/i18n/tr.po
  stock_available_sale/i18n/tr_TR.po
  stock_available_sale/i18n/vi_VN.po
  stock_available_sale/i18n/zh_CN.po
  stock_available_sale/models/__init__.py
  stock_available_sale/models/product_product.py
  stock_available_sale/models/product_template.py
  stock_available_sale/readme/CONTRIBUTORS.rst
  stock_available_sale/readme/DESCRIPTION.rst
  stock_available_sale/readme/ROADMAP.rst
  stock_available_sale/readme/USAGE.rst
  stock_available_sale/static/description/icon.png
  stock_available_sale/tests/__init__.py
  stock_available_sale/tests/test_quoted_qty.py
  stock_available_sale/views/product_template_view.xml
  stock_secondary_unit/tests/test_stock_secondary_unit.py
Labels: 12.0.project_mi_465

#371 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  README.md
  purchase_packaging/__manifest__.py
  purchase_packaging/migrations/10.0.1.0.9/post-migrate.py
  purchase_packaging/models/purchase_order_line.py
  purchase_packaging/tests/test_purchase_order_line.py
Labels: 10.0

#372 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_reserve_rule/odoo/addons/stock_reserve_rule
  setup/stock_reserve_rule/setup.py
  stock_reserve_rule/README.rst
  stock_reserve_rule/__init__.py
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/demo/product_demo.xml
  stock_reserve_rule/demo/stock_inventory_demo.xml
  stock_reserve_rule/demo/stock_location_demo.xml
  stock_reserve_rule/demo/stock_picking_demo.xml
  stock_reserve_rule/demo/stock_reserve_rule_demo.xml
  stock_reserve_rule/i18n/stock_reserve_rule.pot
  stock_reserve_rule/models/__init__.py
  stock_reserve_rule/models/stock_location.py
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/models/stock_quant.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/readme/CONFIGURE.rst
  stock_reserve_rule/readme/CONTRIBUTORS.rst
  stock_reserve_rule/readme/DESCRIPTION.rst
  stock_reserve_rule/readme/USAGE.rst
  stock_reserve_rule/security/ir.model.access.csv
  stock_reserve_rule/security/stock_reserve_rule_security.xml
  stock_reserve_rule/static/description/icon.png
  stock_reserve_rule/static/description/index.html
  stock_reserve_rule/tests/__init__.py
  stock_reserve_rule/tests/test_reserve_rule.py
  stock_reserve_rule/views/stock_reserve_rule_views.xml
Labels: 12.0

#373 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  sale_stock_info_popup/__manifest__.py
  sale_stock_info_popup/i18n/es.po
  sale_stock_info_popup/i18n/sale_stock_info_popup.pot
  sale_stock_info_popup/models/sale_order.py
Labels: 12.0
