Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-10, with the labels that each got.

#614 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_cycle_count/__manifest__.py
  stock_cycle_count/models/stock_location.py
Labels: 13.0

#617 Merging 12.0 into 12.0.project_MI_465
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/models/sale_order.py
  stock_available/i18n/it.po
  stock_move_location/i18n/ja.po
  stock_move_packaging_qty/__manifest__.py
  stock_quant_manual_assign/i18n/ja.po
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/stock_move.py
Labels: 12.0.project_mi_465

#618 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_orderpoint_manual_procurement/odoo/addons/stock_orderpoint_manual_procurement
  setup/stock_orderpoint_manual_procurement/setup.py
  stock_orderpoint_manual_procurement/README.rst
  stock_orderpoint_manual_procurement/__init__.py
  stock_orderpoint_manual_procurement/__manifest__.py
  stock_orderpoint_manual_procurement/demo/product.xml
  stock_orderpoint_manual_procurement/i18n/stock_orderpoint_manual_procurement.pot
  stock_orderpoint_manual_procurement/i18n/zh_CN.po
  stock_orderpoint_manual_procurement/models/__init__.py
  stock_orderpoint_manual_procurement/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement/readme/CONFIGURE.rst
  stock_orderpoint_manual_procurement/readme/CONTRIBUTORS.rst
  stock_orderpoint_manual_procurement/readme/CREDITS.rst
  stock_orderpoint_manual_procurement/readme/DESCRIPTION.rst
  stock_orderpoint_manual_procurement/readme/USAGE.rst
  stock_orderpoint_manual_procurement/security/ir.model.access.csv
  stock_orderpoint_manual_procurement/security/stock_orderpoint_manual_procurement_security.xml
  stock_orderpoint_manual_procurement/static/description/icon.png
  stock_orderpoint_manual_procurement/static/description/index.html
  stock_orderpoint_manual_procurement/tests/__init__.py
  stock_orderpoint_manual_procurement/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement/views/stock_warehouse_orderpoint_view.xml
  stock_orderpoint_manual_procurement/wizards/__init__.py
  stock_orderpoint_manual_procurement/wizards/make_procurement_orderpoint.py
  stock_orderpoint_manual_procurement/wizards/make_procurement_orderpoint_view.xml
Labels: 14.0

#620 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_warehouse_calendar/i18n/it.po
Labels: 14.0

#635 Updating from latest OCA 13.0
  procurement_auto_create_group/README.rst
  procurement_auto_create_group/__manifest__.py
  procurement_auto_create_group/i18n/cs_CZ.po
  procurement_auto_create_group/i18n/de.po
  procurement_auto_create_group/i18n/es.po
  procurement_auto_create_group/i18n/es_MX.po
  procurement_auto_create_group/i18n/fr.po
  procurement_auto_create_group/i18n/hr.po
  procurement_auto_create_group/i18n/it.po
  procurement_auto_create_group/i18n/procurement_auto_create_group.pot
  procurement_auto_create_group/i18n/pt_BR.po
  procurement_auto_create_group/i18n/pt_PT.po
  procurement_auto_create_group/i18n/ro.po
  procurement_auto_create_group/i18n/sk.po
  procurement_auto_create_group/i18n/sl.po
  procurement_auto_create_group/i18n/tr_TR.po
  procurement_auto_create_group/i18n/vi_VN.po
  procurement_auto_create_group/i18n/zh_CN.po
  procurement_auto_create_group/models/__init__.py
  procurement_auto_create_group/models/procurement_group.py
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/readme/CONTRIBUTORS.rst
  procurement_auto_create_group/static/description/index.html
  procurement_auto_create_group/tests/test_auto_create.py
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/models/sale_order.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  stock_request/__manifest__.py
  stock_request/security/ir.model.access.csv
Labels: 13.0.project_mi_465
