Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-09, with the labels that each got.

#585 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_vertical_lift_kardex/__manifest__.py
  stock_vertical_lift_kardex/proxy/README.rst
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
Labels: 13.0

#586 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_archive_constraint/odoo/addons/stock_archive_constraint
  setup/stock_archive_constraint/setup.py
  stock_archive_constraint/README.rst
  stock_archive_constraint/__init__.py
  stock_archive_constraint/__manifest__.py
  stock_archive_constraint/i18n/es.po
  stock_archive_constraint/i18n/stock_archive_constraint.pot
  stock_archive_constraint/models/__init__.py
  stock_archive_constraint/models/product_product.py
  stock_archive_constraint/models/product_template.py
  stock_archive_constraint/models/stock_location.py
  stock_archive_constraint/readme/CONTRIBUTORS.rst
  stock_archive_constraint/readme/DESCRIPTION.rst
  stock_archive_constraint/readme/USAGE.rst
  stock_archive_constraint/static/description/icon.png
  stock_archive_constraint/static/description/index.html
  stock_archive_constraint/tests/__init__.py
  stock_archive_constraint/tests/test_location_archive_constraint.py
  stock_move_location/i18n/ja.po
  stock_move_location/i18n/ja_JP.po
Labels: 14.0

#587 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/data/stock_data.xml
  stock_mts_mto_rule/migrations/13.0.1.3.0/pre-migration.py
Labels: 13.0

#588 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_production_lot_quantity_tree/odoo/addons/stock_production_lot_quantity_tree
  setup/stock_production_lot_quantity_tree/setup.py
  stock_production_lot_quantity_tree/README.rst
  stock_production_lot_quantity_tree/__init__.py
  stock_production_lot_quantity_tree/__manifest__.py
  stock_production_lot_quantity_tree/i18n/stock_production_lot_quantity_tree.pot
  stock_production_lot_quantity_tree/readme/CONTRIBUTORS.rst
  stock_production_lot_quantity_tree/readme/DESCRIPTION.rst
  stock_production_lot_quantity_tree/static/description/icon.png
  stock_production_lot_quantity_tree/static/description/index.html
  stock_production_lot_quantity_tree/views/stock_production_lot.xml
Labels: 13.0

#589 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_available_unreserved/odoo/addons/stock_available_unreserved
  setup/stock_available_unreserved/setup.py
  stock_available_unreserved/README.rst
  stock_available_unreserved/__init__.py
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/i18n/ar.po
  stock_available_unreserved/i18n/ca.po
  stock_available_unreserved/i18n/de.po
  stock_available_unreserved/i18n/el_GR.po
  stock_available_unreserved/i18n/es.po
  stock_available_unreserved/i18n/es_ES.po
  stock_available_unreserved/i18n/es_MX.po
  stock_available_unreserved/i18n/eu.po
  stock_available_unreserved/i18n/fi.po
  stock_available_unreserved/i18n/fr.po
  stock_available_unreserved/i18n/fr_CH.po
  stock_available_unreserved/i18n/fr_FR.po
  stock_available_unreserved/i18n/gl.po
  stock_available_unreserved/i18n/hr.po
  stock_available_unreserved/i18n/hr_HR.po
  stock_available_unreserved/i18n/it.po
  stock_available_unreserved/i18n/nl.po
  stock_available_unreserved/i18n/nl_NL.po
  stock_available_unreserved/i18n/pt.po
  stock_available_unreserved/i18n/pt_BR.po
  stock_available_unreserved/i18n/ro.po
  stock_available_unreserved/i18n/ru.po
  stock_available_unreserved/i18n/sl.po
  stock_available_unreserved/i18n/stock_available_unreserved.pot
  stock_available_unreserved/i18n/tr.po
  stock_available_unreserved/i18n/tr_TR.po
  stock_available_unreserved/i18n/vi_VN.po
  stock_available_unreserved/i18n/zh_CN.po
  stock_available_unreserved/models/__init__.py
  stock_available_unreserved/models/product_product.py
  stock_available_unreserved/models/product_template.py
  stock_available_unreserved/models/stock_quant.py
  stock_available_unreserved/readme/CONTRIBUTORS.rst
  stock_available_unreserved/readme/DESCRIPTION.rst
  stock_available_unreserved/static/description/icon.png
  stock_available_unreserved/static/description/index.html
  stock_available_unreserved/tests/__init__.py
  stock_available_unreserved/tests/test_stock_available_unreserved.py
  stock_available_unreserved/views/product_view.xml
  stock_available_unreserved/views/stock_quant_view.xml
  stock_move_location/i18n/fr.po
  stock_move_location/i18n/fr_FR.po
  stock_request/__manifest__.py
  stock_request/security/ir.model.access.csv
Labels: 14.0

#590 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_move_location/i18n/fr.po
Labels: 14.0

#591 Merging 13.0 into 13.0.project_MI_465
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_production_lot_quantity_tree/odoo/addons/stock_production_lot_quantity_tree
  setup/stock_production_lot_quantity_tree/setup.py
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/data/stock_data.xml
  stock_mts_mto_rule/migrations/13.0.1.3.0/pre-migration.py
  stock_production_lot_quantity_tree/README.rst
  stock_production_lot_quantity_tree/__init__.py
  stock_production_lot_quantity_tree/__manifest__.py
  stock_production_lot_quantity_tree/i18n/stock_production_lot_quantity_tree.pot
  stock_production_lot_quantity_tree/readme/CONTRIBUTORS.rst
  stock_production_lot_quantity_tree/readme/DESCRIPTION.rst
  stock_production_lot_quantity_tree/static/description/icon.png
  stock_production_lot_quantity_tree/static/description/index.html
  stock_production_lot_quantity_tree/views/stock_production_lot.xml
  stock_vertical_lift_kardex/__manifest__.py
  stock_vertical_lift_kardex/proxy/README.rst
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
Labels: 13.0.project_mi_465

#592 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_move_packaging_qty/__manifest__.py
Labels: 12.0

#593 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  oca_dependencies.txt
  sale_automatic_workflow_reserve_sale_stock/README.rst
  sale_automatic_workflow_reserve_sale_stock/__init__.py
  sale_automatic_workflow_reserve_sale_stock/__manifest__.py
  sale_automatic_workflow_reserve_sale_stock/i18n/es.po
  sale_automatic_workflow_reserve_sale_stock/i18n/sale_automatic_workflow_reserve_sale_stock.pot
  sale_automatic_workflow_reserve_sale_stock/i18n/sale_automatic_workflow_stock_reserve.pot
  sale_automatic_workflow_reserve_sale_stock/models/__init__.py
  sale_automatic_workflow_reserve_sale_stock/models/automatic_workflow_job.py
  sale_automatic_workflow_reserve_sale_stock/models/sale_workflow_process.py
  sale_automatic_workflow_reserve_sale_stock/readme/CONFIGURE.rst
  sale_automatic_workflow_reserve_sale_stock/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_reserve_sale_stock/readme/DESCRIPTION.rst
  sale_automatic_workflow_reserve_sale_stock/readme/USAGE.rst
  sale_automatic_workflow_reserve_sale_stock/static/description/icon.png
  sale_automatic_workflow_reserve_sale_stock/static/description/index.html
  sale_automatic_workflow_reserve_sale_stock/tests/__init__.py
  sale_automatic_workflow_reserve_sale_stock/tests/test_sale_automatic_workflow_stock_reserve.py
  sale_automatic_workflow_reserve_sale_stock/views/sale_workflow_process_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_automatic_workflow_reserve_sale_stock/odoo/addons/sale_automatic_workflow_reserve_sale_stock
  setup/sale_automatic_workflow_reserve_sale_stock/setup.py
Labels: 13.0

#595 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available/i18n/it.po
Labels: 12.0

#596 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_measuring_device_zippcube/odoo/addons/stock_measuring_device_zippcube
  setup/stock_measuring_device_zippcube/setup.py
  stock_measuring_device_zippcube/README.rst
  stock_measuring_device_zippcube/__init__.py
  stock_measuring_device_zippcube/__manifest__.py
  stock_measuring_device_zippcube/components/__init__.py
  stock_measuring_device_zippcube/components/zippcube_device_component.py
  stock_measuring_device_zippcube/controllers/__init__.py
  stock_measuring_device_zippcube/controllers/main.py
  stock_measuring_device_zippcube/i18n/stock_measuring_device_zippcube.pot
  stock_measuring_device_zippcube/models/__init__.py
  stock_measuring_device_zippcube/models/measuring_device.py
  stock_measuring_device_zippcube/readme/CONFIGURE.rst
  stock_measuring_device_zippcube/readme/CONTRIBUTORS.rst
  stock_measuring_device_zippcube/readme/CREDITS.rst
  stock_measuring_device_zippcube/readme/DESCRIPTION.rst
  stock_measuring_device_zippcube/readme/INSTALL.rst
  stock_measuring_device_zippcube/readme/ROADMAP.rst
  stock_measuring_device_zippcube/readme/USAGE.rst
  stock_measuring_device_zippcube/scripts/measurement.sh
  stock_measuring_device_zippcube/static/description/icon.png
  stock_measuring_device_zippcube/static/description/index.html
  stock_measuring_device_zippcube/tests/__init__.py
  stock_measuring_device_zippcube/tests/test_zippcube_wizard.py
Labels: 14.0

#597 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_available_mrp/models/product_product.py
Labels: 13.0

#598 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_quant_manual_assign/i18n/ja.po
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/stock_move.py
Labels: 12.0

#600 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_quant_manual_assign/i18n/fr.po
Labels: 14.0

#601 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_cycle_count/__manifest__.py
  stock_cycle_count/views/stock_cycle_count_rule_view.xml
Labels: 13.0

#602 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/models/sale_order.py
Labels: 12.0

#603 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_bin_name/odoo/addons/stock_location_bin_name
  setup/stock_location_bin_name/setup.py
  setup/stock_vertical_lift_kardex/odoo/addons/stock_vertical_lift_kardex
  setup/stock_vertical_lift_kardex/setup.py
  stock_location_bin_name/README.rst
  stock_location_bin_name/__init__.py
  stock_location_bin_name/__manifest__.py
  stock_location_bin_name/i18n/stock_location_bin_name.pot
  stock_location_bin_name/models/__init__.py
  stock_location_bin_name/models/stock_location.py
  stock_location_bin_name/readme/CONTRIBUTORS.rst
  stock_location_bin_name/readme/CREDITS.rst
  stock_location_bin_name/readme/DESCRIPTION.rst
  stock_location_bin_name/static/description/icon.png
  stock_location_bin_name/static/description/index.html
  stock_location_bin_name/views/stock_location.xml
  stock_vertical_lift_kardex/README.rst
  stock_vertical_lift_kardex/__init__.py
  stock_vertical_lift_kardex/__manifest__.py
  stock_vertical_lift_kardex/i18n/stock_vertical_lift_kardex.pot
  stock_vertical_lift_kardex/models/__init__.py
  stock_vertical_lift_kardex/models/stock_location.py
  stock_vertical_lift_kardex/models/vertical_lift_shuttle.py
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
  stock_vertical_lift_kardex/proxy/requirements.txt
  stock_vertical_lift_kardex/proxy/test.py
  stock_vertical_lift_kardex/readme/CONTRIBUTORS.rst
  stock_vertical_lift_kardex/readme/CREDITS.rst
  stock_vertical_lift_kardex/readme/DESCRIPTION.rst
  stock_vertical_lift_kardex/readme/ROADMAP.rst
  stock_vertical_lift_kardex/requirements.txt
  stock_vertical_lift_kardex/static/description/icon.png
  stock_vertical_lift_kardex/static/description/index.html
Labels: 14.0

#604 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_lot_filter_available/__manifest__.py
  stock_lot_filter_available/models/stock_production_lot.py
  stock_lot_filter_available/tests/test_stock_lot_filter_available.py
Labels: 13.0

#605 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_orderpoint_purchase_link/odoo/addons/stock_orderpoint_purchase_link
  setup/stock_orderpoint_purchase_link/setup.py
  setup/stock_vertical_lift_server_env/odoo/addons/stock_vertical_lift_server_env
  setup/stock_vertical_lift_server_env/setup.py
  stock_orderpoint_purchase_link/README.rst
  stock_orderpoint_purchase_link/__init__.py
  stock_orderpoint_purchase_link/__manifest__.py
  stock_orderpoint_purchase_link/i18n/stock_orderpoint_purchase_link.pot
  stock_orderpoint_purchase_link/i18n/zh_CN.po
  stock_orderpoint_purchase_link/models/__init__.py
  stock_orderpoint_purchase_link/models/purchase_order_line.py
  stock_orderpoint_purchase_link/models/stock_rule.py
  stock_orderpoint_purchase_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_purchase_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_purchase_link/readme/CREDITS.rst
  stock_orderpoint_purchase_link/readme/DESCRIPTION.rst
  stock_orderpoint_purchase_link/static/description/icon.png
  stock_orderpoint_purchase_link/static/description/index.html
  stock_orderpoint_purchase_link/tests/__init__.py
  stock_orderpoint_purchase_link/tests/test_stock_orderpoint_purchase_link.py
  stock_orderpoint_purchase_link/views/purchase_order_views.xml
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/i18n/stock_packaging_calculator.pot
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/common.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
  stock_packaging_calculator/tests/utils.py
  stock_vertical_lift_server_env/README.rst
  stock_vertical_lift_server_env/__init__.py
  stock_vertical_lift_server_env/__manifest__.py
  stock_vertical_lift_server_env/i18n/stock_vertical_lift_server_env.pot
  stock_vertical_lift_server_env/models/__init__.py
  stock_vertical_lift_server_env/models/vertical_lift_shuttle.py
  stock_vertical_lift_server_env/readme/CONTRIBUTORS.rst
  stock_vertical_lift_server_env/readme/CREDITS.rst
  stock_vertical_lift_server_env/readme/DESCRIPTION.rst
  stock_vertical_lift_server_env/static/description/icon.png
  stock_vertical_lift_server_env/static/description/index.html
Labels: 14.0

#606 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_location_last_inventory_date/__manifest__.py
  stock_location_last_inventory_date/i18n/stock_location_last_inventory_date.pot
  stock_location_last_inventory_date/models/stock_location.py
  stock_location_last_inventory_date/tests/test_stock_location.py
  stock_location_last_inventory_date/views/stock_location_views.xml
Labels: 13.0

#607 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_vertical_lift_storage_type/odoo/addons/stock_vertical_lift_storage_type
  setup/stock_vertical_lift_storage_type/setup.py
  stock_vertical_lift_storage_type/README.rst
  stock_vertical_lift_storage_type/__init__.py
  stock_vertical_lift_storage_type/__manifest__.py
  stock_vertical_lift_storage_type/i18n/stock_vertical_lift_storage_type.pot
  stock_vertical_lift_storage_type/models/__init__.py
  stock_vertical_lift_storage_type/models/stock_location.py
  stock_vertical_lift_storage_type/models/stock_location_tray_type.py
  stock_vertical_lift_storage_type/models/stock_quant.py
  stock_vertical_lift_storage_type/models/vertical_lift_operation_put.py
  stock_vertical_lift_storage_type/readme/CONTRIBUTORS.rst
  stock_vertical_lift_storage_type/readme/CREDITS.rst
  stock_vertical_lift_storage_type/readme/DESCRIPTION.rst
  stock_vertical_lift_storage_type/static/description/icon.png
  stock_vertical_lift_storage_type/static/description/index.html
  stock_vertical_lift_storage_type/tests/__init__.py
  stock_vertical_lift_storage_type/tests/common.py
  stock_vertical_lift_storage_type/tests/test_put.py
  stock_vertical_lift_storage_type/tests/test_stock_location.py
  stock_vertical_lift_storage_type/tests/test_tray_type.py
  stock_vertical_lift_storage_type/views/stock_location_tray_type_views.xml
  stock_vertical_lift_storage_type/views/stock_location_views.xml
Labels: 14.0

#608 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_product_qty_by_packaging/odoo/addons/stock_product_qty_by_packaging
  setup/stock_product_qty_by_packaging/setup.py
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/__init__.py
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/i18n/stock_product_qty_by_packaging.pot
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_inventory_line.py
  stock_product_qty_by_packaging/models/stock_move.py
  stock_product_qty_by_packaging/models/stock_move_line.py
  stock_product_qty_by_packaging/models/stock_quant.py
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_product_qty_by_packaging/readme/CREDITS.rst
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/static/description/icon.png
  stock_product_qty_by_packaging/static/description/index.html
  stock_product_qty_by_packaging/tests/__init__.py
  stock_product_qty_by_packaging/tests/test_stock.py
  stock_product_qty_by_packaging/views/stock_inventory_line.xml
  stock_product_qty_by_packaging/views/stock_picking.xml
Labels: 14.0

#609 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_last_inventory_date/odoo/addons/stock_location_last_inventory_date
  setup/stock_location_last_inventory_date/setup.py
  setup/stock_packaging_calculator_packaging_type/odoo/addons/stock_packaging_calculator_packaging_type
  setup/stock_packaging_calculator_packaging_type/setup.py
  stock_location_last_inventory_date/README.rst
  stock_location_last_inventory_date/__init__.py
  stock_location_last_inventory_date/__manifest__.py
  stock_location_last_inventory_date/i18n/stock_location_last_inventory_date.pot
  stock_location_last_inventory_date/models/__init__.py
  stock_location_last_inventory_date/models/stock_location.py
  stock_location_last_inventory_date/readme/CONTRIBUTORS.rst
  stock_location_last_inventory_date/readme/CREDITS.rst
  stock_location_last_inventory_date/readme/DESCRIPTION.rst
  stock_location_last_inventory_date/static/description/icon.png
  stock_location_last_inventory_date/static/description/index.html
  stock_location_last_inventory_date/tests/__init__.py
  stock_location_last_inventory_date/tests/test_stock_location.py
  stock_location_last_inventory_date/views/stock_location_views.xml
  stock_packaging_calculator_packaging_type/README.rst
  stock_packaging_calculator_packaging_type/__init__.py
  stock_packaging_calculator_packaging_type/__manifest__.py
  stock_packaging_calculator_packaging_type/i18n/stock_packaging_calculator_packaging_type.pot
  stock_packaging_calculator_packaging_type/models/__init__.py
  stock_packaging_calculator_packaging_type/models/product.py
  stock_packaging_calculator_packaging_type/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator_packaging_type/readme/CONTRIBUTORS.rst
  stock_packaging_calculator_packaging_type/readme/CREDITS.rst
  stock_packaging_calculator_packaging_type/readme/DESCRIPTION.rst
  stock_packaging_calculator_packaging_type/static/description/icon.png
  stock_packaging_calculator_packaging_type/static/description/index.html
  stock_packaging_calculator_packaging_type/tests/__init__.py
  stock_packaging_calculator_packaging_type/tests/test_packaging_by_qty.py
Labels: 14.0

#610 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_request/__manifest__.py
  stock_request/models/stock_request.py
Labels: 14.0

#611 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_move_location/i18n/ja.po
Labels: 12.0

#612 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request/__manifest__.py
  stock_request/i18n/ca.po
  stock_request/i18n/de.po
  stock_request/i18n/el_GR.po
  stock_request/i18n/es.po
  stock_request/i18n/es_ES.po
  stock_request/i18n/eu.po
  stock_request/i18n/fi.po
  stock_request/i18n/fr.po
  stock_request/i18n/fr_CH.po
  stock_request/i18n/fr_FR.po
  stock_request/i18n/gl.po
  stock_request/i18n/hr.po
  stock_request/i18n/hr_HR.po
  stock_request/i18n/it.po
  stock_request/i18n/nl.po
  stock_request/i18n/nl_NL.po
  stock_request/i18n/pt.po
  stock_request/i18n/pt_BR.po
  stock_request/i18n/ro.po
  stock_request/i18n/ru.po
  stock_request/i18n/sl.po
  stock_request/i18n/stock_request.pot
  stock_request/i18n/tr.po
  stock_request/i18n/tr_TR.po
  stock_request/i18n/vi_VN.po
  stock_request/i18n/zh_CN.po
  stock_request/views/stock_request_report.xml
Labels: 13.0

#613 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_orderpoint_route/odoo/addons/stock_orderpoint_route
  setup/stock_orderpoint_route/setup.py
  stock_orderpoint_route/README.rst
  stock_orderpoint_route/__init__.py
  stock_orderpoint_route/__manifest__.py
  stock_orderpoint_route/i18n/stock_orderpoint_route.pot
  stock_orderpoint_route/models/__init__.py
  stock_orderpoint_route/models/stock_warehouse_orderpoint.py
  stock_orderpoint_route/readme/CONTRIBUTORS.rst
  stock_orderpoint_route/readme/CREDITS.rst
  stock_orderpoint_route/readme/DESCRIPTION.rst
  stock_orderpoint_route/readme/USAGE.rst
  stock_orderpoint_route/static/description/icon.png
  stock_orderpoint_route/static/description/index.html
  stock_orderpoint_route/tests/__init__.py
  stock_orderpoint_route/tests/test_stock_orderpoint_route.py
  stock_orderpoint_route/views/stock_warehouse_orderpoint_views.xml
Labels: 14.0
