Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-03, with the labels that each got.

#472 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request_tier_validation/i18n/zh_CN.po
Labels: 13.0

#473 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_available_immediately/odoo/addons/stock_available_immediately
  setup/stock_available_immediately/setup.py
  stock_available_immediately/README.rst
  stock_available_immediately/__init__.py
  stock_available_immediately/__manifest__.py
  stock_available_immediately/i18n/ca.po
  stock_available_immediately/i18n/cs_CZ.po
  stock_available_immediately/i18n/de.po
  stock_available_immediately/i18n/el_GR.po
  stock_available_immediately/i18n/es.po
  stock_available_immediately/i18n/es_ES.po
  stock_available_immediately/i18n/es_MX.po
  stock_available_immediately/i18n/eu.po
  stock_available_immediately/i18n/fi.po
  stock_available_immediately/i18n/fr.po
  stock_available_immediately/i18n/fr_CH.po
  stock_available_immediately/i18n/fr_FR.po
  stock_available_immediately/i18n/gl.po
  stock_available_immediately/i18n/hr.po
  stock_available_immediately/i18n/hr_HR.po
  stock_available_immediately/i18n/it.po
  stock_available_immediately/i18n/nl.po
  stock_available_immediately/i18n/nl_NL.po
  stock_available_immediately/i18n/pt.po
  stock_available_immediately/i18n/pt_BR.po
  stock_available_immediately/i18n/ro.po
  stock_available_immediately/i18n/ru.po
  stock_available_immediately/i18n/sl.po
  stock_available_immediately/i18n/stock_available_immediately.pot
  stock_available_immediately/i18n/tr.po
  stock_available_immediately/i18n/tr_TR.po
  stock_available_immediately/i18n/vi_VN.po
  stock_available_immediately/i18n/zh_CN.po
  stock_available_immediately/models/__init__.py
  stock_available_immediately/models/product_product.py
  stock_available_immediately/readme/CONTRIBUTORS.rst
  stock_available_immediately/readme/DESCRIPTION.rst
  stock_available_immediately/static/description/icon.png
  stock_available_immediately/static/description/index.html
  stock_available_immediately/tests/__init__.py
  stock_available_immediately/tests/test_stock_available_immediately.py
Labels: 13.0

#476 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_orderpoint_generator/__manifest__.py
  stock_orderpoint_generator/models/product.py
  stock_orderpoint_generator/tests/test_orderpoint_generator.py
Labels: 12.0

#477 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  scrap_reason_code/README.rst
  scrap_reason_code/__init__.py
  scrap_reason_code/__manifest__.py
  scrap_reason_code/i18n/scrap_reason_code.pot
  scrap_reason_code/models/__init__.py
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_move.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONFIGURE.rst
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/readme/CREDITS.rst
  scrap_reason_code/readme/DESCRIPTION.rst
  scrap_reason_code/readme/ROADMAP.rst
  scrap_reason_code/readme/USAGE.rst
  scrap_reason_code/security/ir.model.access.csv
  scrap_reason_code/static/description/icon.png
  scrap_reason_code/static/description/index.html
  scrap_reason_code/tests/__init__.py
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_move_views.xml
  scrap_reason_code/views/stock_scrap_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/scrap_reason_code/odoo/addons/scrap_reason_code
  setup/scrap_reason_code/setup.py
  setup/stock_inventory_include_exhausted/odoo/addons/stock_inventory_include_exhausted
  stock_inventory_include_exhausted/__init__.py
  stock_inventory_include_exhausted/__manifest__.py
  stock_inventory_include_exhausted/i18n/es.po
  stock_inventory_include_exhausted/i18n/stock_inventory_include_exhausted.pot
  stock_inventory_include_exhausted/models/__init__.py
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/readme/CONTRIBUTORS.rst
  stock_inventory_include_exhausted/readme/DESCRIPTION.rst
  stock_inventory_include_exhausted/readme/USAGE.rst
  stock_inventory_include_exhausted/tests/__init__.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
  stock_inventory_include_exhausted/views/stock_inventory_view.xml
Labels: 14.0

#475 [t119088] migration of stock_available_sale in v13
  stock_available_sale/README.rst
  stock_available_sale/__init__.py
  stock_available_sale/__manifest__.py
  stock_available_sale/i18n/ca.po
  stock_available_sale/i18n/cs_CZ.po
  stock_available_sale/i18n/de.po
  stock_available_sale/i18n/el_GR.po
  stock_available_sale/i18n/es.po
  stock_available_sale/i18n/es_ES.po
  stock_available_sale/i18n/es_MX.po
  stock_available_sale/i18n/eu.po
  stock_available_sale/i18n/fi.po
  stock_available_sale/i18n/fr.po
  stock_available_sale/i18n/fr_CH.po
  stock_available_sale/i18n/fr_FR.po
  stock_available_sale/i18n/gl.po
  stock_available_sale/i18n/hr.po
  stock_available_sale/i18n/hr_HR.po
  stock_available_sale/i18n/it.po
  stock_available_sale/i18n/nl.po
  stock_available_sale/i18n/nl_NL.po
  stock_available_sale/i18n/pt.po
  stock_available_sale/i18n/pt_BR.po
  stock_available_sale/i18n/ro.po
  stock_available_sale/i18n/ru.po
  stock_available_sale/i18n/sl.po
  stock_available_sale/i18n/stock_available_sale.pot
  stock_available_sale/i18n/tr.po
  stock_available_sale/i18n/tr_TR.po
  stock_available_sale/i18n/vi_VN.po
  stock_available_sale/i18n/zh_CN.po
  stock_available_sale/models/__init__.py
  stock_available_sale/models/product_product.py
  stock_available_sale/models/product_template.py
  stock_available_sale/readme/CONTRIBUTORS.rst
  stock_available_sale/readme/DESCRIPTION.rst
  stock_available_sale/readme/ROADMAP.rst
  stock_available_sale/readme/USAGE.rst
  stock_available_sale/static/description/icon.png
  stock_available_sale/tests/__init__.py
  stock_available_sale/tests/test_quoted_qty.py
  stock_available_sale/views/product_template_view.xml
Labels: 13.0.project_mi_465, odoo_migration

#480 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_position/odoo/addons/stock_location_position
  setup/stock_location_position/setup.py
  setup/stock_picking_completion_info/odoo/addons/stock_picking_completion_info
  setup/stock_picking_completion_info/setup.py
  stock_location_position/README.rst
  stock_location_position/__init__.py
  stock_location_position/__manifest__.py
  stock_location_position/i18n/stock_location_position.pot
  stock_location_position/models/__init__.py
  stock_location_position/models/stock_location.py
  stock_location_position/readme/CONTRIBUTORS.rst
  stock_location_position/readme/DESCRIPTION.rst
  stock_location_position/static/description/icon.png
  stock_location_position/static/description/index.html
  stock_location_position/views/stock_location.xml
  stock_location_zone/i18n/stock_location_zone.pot
  stock_location_zone/i18n/zh_CN.po
  stock_picking_completion_info/README.rst
  stock_picking_completion_info/__init__.py
  stock_picking_completion_info/__manifest__.py
  stock_picking_completion_info/i18n/stock_picking_completion_info.pot
  stock_picking_completion_info/models/__init__.py
  stock_picking_completion_info/models/stock_picking.py
  stock_picking_completion_info/readme/CONTRIBUTORS.rst
  stock_picking_completion_info/readme/DESCRIPTION.rst
  stock_picking_completion_info/static/description/icon.png
  stock_picking_completion_info/static/description/index.html
  stock_picking_completion_info/tests/__init__.py
  stock_picking_completion_info/tests/test_stock_picking_completion_info.py
  stock_picking_completion_info/views/stock_picking.xml
Labels: 12.0

#481 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_inventory_justification/.eggs/README.txt
  setup/stock_inventory_justification/odoo/addons/stock_inventory_justification
  setup/stock_inventory_justification/setup.py
  stock_inventory_justification/README.rst
  stock_inventory_justification/__init__.py
  stock_inventory_justification/__manifest__.py
  stock_inventory_justification/i18n/stock_inventory_justification.pot
  stock_inventory_justification/models/__init__.py
  stock_inventory_justification/models/stock_inventory.py
  stock_inventory_justification/models/stock_inventory_justification.py
  stock_inventory_justification/readme/CONTRIBUTORS.rst
  stock_inventory_justification/readme/DESCRIPTION.rst
  stock_inventory_justification/readme/USAGE.rst
  stock_inventory_justification/security/security.xml
  stock_inventory_justification/static/description/icon.png
  stock_inventory_justification/static/description/index.html
  stock_inventory_justification/views/stock_inventory.xml
  stock_inventory_justification/views/stock_inventory_justification.xml
Labels: 13.0

#482 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request_analytic/i18n/pt_BR.po
  stock_request_analytic/i18n/stock_request_analytic.pot
  stock_request_analytic/i18n/zh_CN.po
  stock_request_analytic/models/stock_request.py
  stock_request_analytic/models/stock_request_order.py
  stock_request_analytic/models/stock_rule.py
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: 12.0

#483 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request_purchase/__manifest__.py
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: 12.0

#484 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_vertical_lift_empty_tray_check/odoo/addons/stock_vertical_lift_empty_tray_check
  setup/stock_vertical_lift_empty_tray_check/setup.py
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/models/vertical_lift_operation_put.py
  stock_vertical_lift_empty_tray_check/README.rst
  stock_vertical_lift_empty_tray_check/__init__.py
  stock_vertical_lift_empty_tray_check/__manifest__.py
  stock_vertical_lift_empty_tray_check/i18n/stock_vertical_lift_empty_tray_check.pot
  stock_vertical_lift_empty_tray_check/models/__init__.py
  stock_vertical_lift_empty_tray_check/models/res_config_settings.py
  stock_vertical_lift_empty_tray_check/models/vertical_lift_operation_pick.py
  stock_vertical_lift_empty_tray_check/models/vertical_lift_operation_pick_zero_check.py
  stock_vertical_lift_empty_tray_check/readme/CONFIGURE.rst
  stock_vertical_lift_empty_tray_check/readme/CONTRIBUTORS.rst
  stock_vertical_lift_empty_tray_check/readme/DESCRIPTION.rst
  stock_vertical_lift_empty_tray_check/static/description/icon.png
  stock_vertical_lift_empty_tray_check/static/description/index.html
  stock_vertical_lift_empty_tray_check/tests/__init__.py
  stock_vertical_lift_empty_tray_check/tests/test_pick.py
  stock_vertical_lift_empty_tray_check/views/res_config_setting_views.xml
  stock_vertical_lift_empty_tray_check/views/vertical_lift_operation_pick_zero_check_views.xml
Labels: 13.0

#486 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_available_immediately/odoo/addons/stock_available_immediately
  setup/stock_available_immediately/setup.py
  stock_available_immediately/README.rst
  stock_available_immediately/__init__.py
  stock_available_immediately/__manifest__.py
  stock_available_immediately/i18n/ca.po
  stock_available_immediately/i18n/cs_CZ.po
  stock_available_immediately/i18n/de.po
  stock_available_immediately/i18n/el_GR.po
  stock_available_immediately/i18n/es.po
  stock_available_immediately/i18n/es_ES.po
  stock_available_immediately/i18n/es_MX.po
  stock_available_immediately/i18n/eu.po
  stock_available_immediately/i18n/fi.po
  stock_available_immediately/i18n/fr.po
  stock_available_immediately/i18n/fr_CH.po
  stock_available_immediately/i18n/fr_FR.po
  stock_available_immediately/i18n/gl.po
  stock_available_immediately/i18n/hr.po
  stock_available_immediately/i18n/hr_HR.po
  stock_available_immediately/i18n/it.po
  stock_available_immediately/i18n/nl.po
  stock_available_immediately/i18n/nl_NL.po
  stock_available_immediately/i18n/pt.po
  stock_available_immediately/i18n/pt_BR.po
  stock_available_immediately/i18n/ro.po
  stock_available_immediately/i18n/ru.po
  stock_available_immediately/i18n/sl.po
  stock_available_immediately/i18n/stock_available_immediately.pot
  stock_available_immediately/i18n/tr.po
  stock_available_immediately/i18n/tr_TR.po
  stock_available_immediately/i18n/vi_VN.po
  stock_available_immediately/i18n/zh_CN.po
  stock_available_immediately/models/__init__.py
  stock_available_immediately/models/product_product.py
  stock_available_immediately/readme/CONTRIBUTORS.rst
  stock_available_immediately/readme/DESCRIPTION.rst
  stock_available_immediately/static/description/icon.png
  stock_available_immediately/static/description/index.html
  stock_available_immediately/tests/__init__.py
  stock_available_immediately/tests/test_stock_available_immediately.py
Labels: 14.0

#489 Updating from latest OCA 12.0
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_position/odoo/addons/stock_location_position
  setup/stock_location_position/setup.py
  setup/stock_picking_completion_info/odoo/addons/stock_picking_completion_info
  setup/stock_picking_completion_info/setup.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_location_position/README.rst
  stock_location_position/__init__.py
  stock_location_position/__manifest__.py
  stock_location_position/i18n/stock_location_position.pot
  stock_location_position/models/__init__.py
  stock_location_position/models/stock_location.py
  stock_location_position/readme/CONTRIBUTORS.rst
  stock_location_position/readme/DESCRIPTION.rst
  stock_location_position/static/description/icon.png
  stock_location_position/static/description/index.html
  stock_location_position/views/stock_location.xml
  stock_location_zone/i18n/stock_location_zone.pot
  stock_location_zone/i18n/zh_CN.po
  stock_orderpoint_generator/__manifest__.py
  stock_orderpoint_generator/models/product.py
  stock_orderpoint_generator/tests/test_orderpoint_generator.py
  stock_picking_completion_info/README.rst
  stock_picking_completion_info/__init__.py
  stock_picking_completion_info/__manifest__.py
  stock_picking_completion_info/i18n/stock_picking_completion_info.pot
  stock_picking_completion_info/models/__init__.py
  stock_picking_completion_info/models/stock_picking.py
  stock_picking_completion_info/readme/CONTRIBUTORS.rst
  stock_picking_completion_info/readme/DESCRIPTION.rst
  stock_picking_completion_info/static/description/icon.png
  stock_picking_completion_info/static/description/index.html
  stock_picking_completion_info/tests/__init__.py
  stock_picking_completion_info/tests/test_stock_picking_completion_info.py
  stock_picking_completion_info/views/stock_picking.xml
  stock_request_analytic/i18n/pt_BR.po
  stock_request_analytic/i18n/stock_request_analytic.pot
  stock_request_analytic/i18n/zh_CN.po
  stock_request_analytic/models/stock_request.py
  stock_request_analytic/models/stock_request_order.py
  stock_request_analytic/models/stock_rule.py
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
  stock_request_purchase/__manifest__.py
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/tests/test_stock_request_purchase.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/views/product_views.xml
Labels: 12.0.project_mi_465

#490 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_helper/odoo/addons/stock_helper
  setup/stock_helper/setup.py
  stock_helper/README.rst
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/i18n/stock_helper.pot
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/readme/DESCRIPTION.rst
  stock_helper/static/description/icon.png
  stock_helper/static/description/index.html
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
Labels: 14.0
