Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-04, with the labels that each got.

#491 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_cycle_count/i18n/id.po
Labels: 12.0

#492 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request_purchase/__manifest__.py
  stock_request_purchase/tests/test_stock_request_purchase.py
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/tests/test_pick.py
Labels: 13.0

#493 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_inventory_preparation_filter/i18n/fr_FR.po
Labels: 14.0

#495 Update 2021-04-13: Updating from 13.0
  stock_cycle_count/i18n/id.po
Labels: 12.0.project_mi_465

#496 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_request_analytic/odoo/addons/stock_request_analytic
  setup/stock_request_analytic/setup.py
  stock_request_analytic/README.rst
  stock_request_analytic/__init__.py
  stock_request_analytic/__manifest__.py
  stock_request_analytic/i18n/pt_BR.po
  stock_request_analytic/i18n/stock_request_analytic.pot
  stock_request_analytic/i18n/zh_CN.po
  stock_request_analytic/models/__init__.py
  stock_request_analytic/models/analytic.py
  stock_request_analytic/models/stock_request.py
  stock_request_analytic/models/stock_request_order.py
  stock_request_analytic/models/stock_rule.py
  stock_request_analytic/readme/CONTRIBUTORS.rst
  stock_request_analytic/readme/DESCRIPTION.rst
  stock_request_analytic/readme/ROADMAP.rst
  stock_request_analytic/readme/USAGE.rst
  stock_request_analytic/security/ir.model.access.csv
  stock_request_analytic/static/description/icon.png
  stock_request_analytic/static/description/index.html
  stock_request_analytic/tests/__init__.py
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/analytic_views.xml
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
Labels: 13.0

#497 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available_mrp/__manifest__.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: 12.0

#499 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request_direction/__manifest__.py
  stock_request_direction/models/stock_request.py
  stock_request_direction/models/stock_request_order.py
Labels: 13.0

#500 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_move_common_dest/odoo/addons/stock_move_common_dest
  setup/stock_move_common_dest/setup.py
  stock_move_common_dest/README.rst
  stock_move_common_dest/__init__.py
  stock_move_common_dest/__manifest__.py
  stock_move_common_dest/i18n/stock_move_common_dest.pot
  stock_move_common_dest/models/__init__.py
  stock_move_common_dest/models/stock_move.py
  stock_move_common_dest/readme/CONTRIBUTORS.rst
  stock_move_common_dest/readme/DESCRIPTION.rst
  stock_move_common_dest/static/description/icon.png
  stock_move_common_dest/static/description/index.html
  stock_move_common_dest/tests/__init__.py
  stock_move_common_dest/tests/test_move_common_dest.py
  stock_move_common_dest/views/stock_move.xml
Labels: 14.0

#501 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request_tier_validation/__manifest__.py
  stock_request_tier_validation/views/stock_request_order_view.xml
Labels: 12.0

#502 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_measuring_device/odoo/addons/stock_measuring_device
  setup/stock_measuring_device/setup.py
  stock_measuring_device/README.rst
  stock_measuring_device/__init__.py
  stock_measuring_device/__manifest__.py
  stock_measuring_device/components/__init__.py
  stock_measuring_device/components/measuring_device_component.py
  stock_measuring_device/data/uom.xml
  stock_measuring_device/i18n/stock_measuring_device.pot
  stock_measuring_device/models/__init__.py
  stock_measuring_device/models/measuring_device.py
  stock_measuring_device/models/product_packaging.py
  stock_measuring_device/models/stock_warehouse.py
  stock_measuring_device/readme/CONFIGURE.rst
  stock_measuring_device/readme/CONTRIBUTORS.rst
  stock_measuring_device/readme/DESCRIPTION.rst
  stock_measuring_device/readme/INSTALL.rst
  stock_measuring_device/readme/ROADMAP.rst
  stock_measuring_device/readme/USAGE.rst
  stock_measuring_device/security/ir.model.access.csv
  stock_measuring_device/static/description/icon.png
  stock_measuring_device/static/description/index.html
  stock_measuring_device/static/src/scss/measuring_wizard.scss
  stock_measuring_device/views/assets.xml
  stock_measuring_device/views/measuring_device_view.xml
  stock_measuring_device/views/menu.xml
  stock_measuring_device/wizard/__init__.py
  stock_measuring_device/wizard/measuring_wizard.py
  stock_measuring_device/wizard/measuring_wizard.xml
  stock_measuring_device/wizard/measuring_wizard_line.py
Labels: 13.0

#503 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request/__manifest__.py
  stock_request/i18n/ca.po
  stock_request/i18n/de.po
  stock_request/i18n/el_GR.po
  stock_request/i18n/es.po
  stock_request/i18n/es_ES.po
  stock_request/i18n/eu.po
  stock_request/i18n/fi.po
  stock_request/i18n/fr.po
  stock_request/i18n/fr_CH.po
  stock_request/i18n/fr_FR.po
  stock_request/i18n/gl.po
  stock_request/i18n/hr.po
  stock_request/i18n/hr_HR.po
  stock_request/i18n/it.po
  stock_request/i18n/nl.po
  stock_request/i18n/nl_NL.po
  stock_request/i18n/pt.po
  stock_request/i18n/pt_BR.po
  stock_request/i18n/ro.po
  stock_request/i18n/ru.po
  stock_request/i18n/sl.po
  stock_request/i18n/stock_request.pot
  stock_request/i18n/tr.po
  stock_request/i18n/tr_TR.po
  stock_request/i18n/vi_VN.po
  stock_request/i18n/zh_CN.po
  stock_request/models/stock_move.py
  stock_request/models/stock_move_line.py
  stock_request/models/stock_request.py
  stock_request/models/stock_request_allocation.py
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
Labels: 13.0

#505 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_measuring_device_zippcube/odoo/addons/stock_measuring_device_zippcube
  setup/stock_measuring_device_zippcube/setup.py
  stock_measuring_device_zippcube/README.rst
  stock_measuring_device_zippcube/__init__.py
  stock_measuring_device_zippcube/__manifest__.py
  stock_measuring_device_zippcube/components/__init__.py
  stock_measuring_device_zippcube/components/zippcube_device_component.py
  stock_measuring_device_zippcube/controllers/__init__.py
  stock_measuring_device_zippcube/controllers/main.py
  stock_measuring_device_zippcube/i18n/stock_measuring_device_zippcube.pot
  stock_measuring_device_zippcube/models/__init__.py
  stock_measuring_device_zippcube/models/measuring_device.py
  stock_measuring_device_zippcube/readme/CONFIGURE.rst
  stock_measuring_device_zippcube/readme/CONTRIBUTORS.rst
  stock_measuring_device_zippcube/readme/DESCRIPTION.rst
  stock_measuring_device_zippcube/readme/INSTALL.rst
  stock_measuring_device_zippcube/readme/ROADMAP.rst
  stock_measuring_device_zippcube/readme/USAGE.rst
  stock_measuring_device_zippcube/scripts/measurement.sh
  stock_measuring_device_zippcube/static/description/icon.png
  stock_measuring_device_zippcube/static/description/index.html
  stock_measuring_device_zippcube/tests/__init__.py
  stock_measuring_device_zippcube/tests/test_zippcube_wizard.py
  stock_request/i18n/stock_request.pot
Labels: 13.0

#506 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_available/__manifest__.py
  stock_available/models/product_product.py
  stock_available/tests/test_stock_available.py
Labels: 14.0

#507 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_request/__manifest__.py
  stock_request/models/stock_request_order.py
Labels: 14.0

#508 Updating from latest OCA 12.0
  stock_available_mrp/__manifest__.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_request_tier_validation/__manifest__.py
  stock_request_tier_validation/views/stock_request_order_view.xml
Labels: 12.0.project_mi_465
