Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-02, with the labels that each got.

#458 [bt#13130] Removed push_rule_auto_create_group
  push_rule_auto_create_group/README.rst
  push_rule_auto_create_group/__init__.py
  push_rule_auto_create_group/__manifest__.py
  push_rule_auto_create_group/models/__init__.py
  push_rule_auto_create_group/models/stock_location_path.py
  push_rule_auto_create_group/readme/CONFIGURE.rst
  push_rule_auto_create_group/readme/CONTRIBUTORS.rst
  push_rule_auto_create_group/readme/DESCRIPTION.rst
  push_rule_auto_create_group/readme/USAGE.rst
  push_rule_auto_create_group/static/description/icon.png
  push_rule_auto_create_group/static/description/index.html
  push_rule_auto_create_group/tests/__init__.py
  push_rule_auto_create_group/tests/test_auto_create.py
  push_rule_auto_create_group/views/stock_location_view.xml
Labels: 13.0.project_mi_465, bug

#460 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_children/odoo/addons/stock_location_children
  setup/stock_location_children/setup.py
  setup/stock_location_last_inventory_date/odoo/addons/stock_location_last_inventory_date
  setup/stock_location_last_inventory_date/setup.py
  stock_available/tests/test_stock_available.py
  stock_location_children/README.rst
  stock_location_children/__init__.py
  stock_location_children/__manifest__.py
  stock_location_children/i18n/stock_location_children.pot
  stock_location_children/models/__init__.py
  stock_location_children/models/stock_location.py
  stock_location_children/readme/CONTRIBUTORS.rst
  stock_location_children/readme/DESCRIPTION.rst
  stock_location_children/static/description/icon.png
  stock_location_children/static/description/index.html
  stock_location_children/tests/__init__.py
  stock_location_children/tests/test_stock_location_children.py
  stock_location_last_inventory_date/README.rst
  stock_location_last_inventory_date/__init__.py
  stock_location_last_inventory_date/__manifest__.py
  stock_location_last_inventory_date/i18n/stock_location_last_inventory_date.pot
  stock_location_last_inventory_date/models/__init__.py
  stock_location_last_inventory_date/models/stock_location.py
  stock_location_last_inventory_date/readme/CONTRIBUTORS.rst
  stock_location_last_inventory_date/readme/DESCRIPTION.rst
  stock_location_last_inventory_date/static/description/icon.png
  stock_location_last_inventory_date/static/description/index.html
  stock_location_last_inventory_date/tests/__init__.py
  stock_location_last_inventory_date/tests/test_stock_location.py
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/data/stock_data.xml
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/i18n/zh_CN.po
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/stock_picking_views.xml
  stock_vertical_lift/README.rst
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/demo/stock_inventory_demo.xml
  stock_vertical_lift/i18n/stock_vertical_lift.pot
  stock_vertical_lift/images/O-BTN.skip.svg
  stock_vertical_lift/models/stock_move_line.py
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/readme/CONFIGURE.rst
  stock_vertical_lift/readme/DEVELOP.rst
  stock_vertical_lift/static/description/index.html
  stock_vertical_lift/tests/common.py
  stock_vertical_lift/tests/test_pick.py
  stock_vertical_lift/views/vertical_lift_operation_base_views.xml
Labels: 13.0

#461 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_free_quantity/odoo/addons/stock_free_quantity
  setup/stock_free_quantity/setup.py
  setup/stock_inventory_include_exhausted/odoo/addons/stock_inventory_include_exhausted
  setup/stock_inventory_include_exhausted/setup.py
  stock_free_quantity/README.rst
  stock_free_quantity/__init__.py
  stock_free_quantity/__manifest__.py
  stock_free_quantity/i18n/stock_free_quantity.pot
  stock_free_quantity/models/__init__.py
  stock_free_quantity/models/product_template.py
  stock_free_quantity/readme/CONTRIBUTORS.rst
  stock_free_quantity/readme/DESCRIPTION.rst
  stock_free_quantity/static/description/icon.png
  stock_free_quantity/static/description/index.html
  stock_free_quantity/tests/__init__.py
  stock_free_quantity/tests/test_template_free_qty.py
  stock_free_quantity/views/product_product_view.xml
  stock_free_quantity/views/product_template_view.xml
  stock_inventory_include_exhausted/README.rst
  stock_inventory_include_exhausted/__init__.py
  stock_inventory_include_exhausted/__manifest__.py
  stock_inventory_include_exhausted/i18n/es.po
  stock_inventory_include_exhausted/i18n/stock_inventory_include_exhausted.pot
  stock_inventory_include_exhausted/models/__init__.py
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/readme/CONTRIBUTORS.rst
  stock_inventory_include_exhausted/readme/DESCRIPTION.rst
  stock_inventory_include_exhausted/readme/USAGE.rst
  stock_inventory_include_exhausted/static/description/icon.png
  stock_inventory_include_exhausted/static/description/index.html
  stock_inventory_include_exhausted/tests/__init__.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
  stock_inventory_include_exhausted/views/stock_inventory_view.xml
Labels: 14.0

#463 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/views/product_views.xml
Labels: 12.0

#466 [t120786] Migration of stock_available_immediately for v13. Backporte…
  stock_available_immediately/README.rst
  stock_available_immediately/__init__.py
  stock_available_immediately/__manifest__.py
  stock_available_immediately/i18n/ca.po
  stock_available_immediately/i18n/cs_CZ.po
  stock_available_immediately/i18n/de.po
  stock_available_immediately/i18n/el_GR.po
  stock_available_immediately/i18n/es.po
  stock_available_immediately/i18n/es_ES.po
  stock_available_immediately/i18n/es_MX.po
  stock_available_immediately/i18n/eu.po
  stock_available_immediately/i18n/fi.po
  stock_available_immediately/i18n/fr.po
  stock_available_immediately/i18n/fr_CH.po
  stock_available_immediately/i18n/fr_FR.po
  stock_available_immediately/i18n/gl.po
  stock_available_immediately/i18n/hr.po
  stock_available_immediately/i18n/hr_HR.po
  stock_available_immediately/i18n/it.po
  stock_available_immediately/i18n/nl.po
  stock_available_immediately/i18n/nl_NL.po
  stock_available_immediately/i18n/pt.po
  stock_available_immediately/i18n/pt_BR.po
  stock_available_immediately/i18n/ro.po
  stock_available_immediately/i18n/ru.po
  stock_available_immediately/i18n/sl.po
  stock_available_immediately/i18n/stock_available_immediately.pot
  stock_available_immediately/i18n/tr.po
  stock_available_immediately/i18n/tr_TR.po
  stock_available_immediately/i18n/vi_VN.po
  stock_available_immediately/i18n/zh_CN.po
  stock_available_immediately/models/__init__.py
  stock_available_immediately/models/product_product.py
  stock_available_immediately/readme/CONTRIBUTORS.rst
  stock_available_immediately/readme/DESCRIPTION.rst
  stock_available_immediately/static/description/icon.png
  stock_available_immediately/static/description/index.html
  stock_available_immediately/tests/__init__.py
  stock_available_immediately/tests/test_stock_available_immediately.py
Labels: 13.0.project_mi_465, feature, odoo_migration

#468 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  sale_stock_available_info_popup/README.rst
  sale_stock_available_info_popup/__init__.py
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/i18n/es.po
  sale_stock_available_info_popup/i18n/sale_stock_available_info_popup.pot
  sale_stock_available_info_popup/i18n/sl.po
  sale_stock_available_info_popup/models/__init__.py
  sale_stock_available_info_popup/models/sale_order.py
  sale_stock_available_info_popup/readme/CONTRIBUTORS.rst
  sale_stock_available_info_popup/readme/DESCRIPTION.rst
  sale_stock_available_info_popup/readme/USAGE.rst
  sale_stock_available_info_popup/static/description/icon.png
  sale_stock_available_info_popup/static/description/index.html
  sale_stock_available_info_popup/static/src/xml/qty_at_date.xml
  sale_stock_available_info_popup/tests/__init__.py
  sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
  sale_stock_available_info_popup/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_available_info_popup/odoo/addons/sale_stock_available_info_popup
  setup/sale_stock_available_info_popup/setup.py
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/i18n/stock_vertical_lift.pot
  stock_vertical_lift/views/vertical_lift_operation_base_views.xml
  stock_vertical_lift/views/vertical_lift_operation_pick_views.xml
Labels: 13.0

#470 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_pull_list/odoo/addons/stock_pull_list
  setup/stock_pull_list/setup.py
  stock_pull_list/README.rst
  stock_pull_list/__init__.py
  stock_pull_list/__manifest__.py
  stock_pull_list/i18n/stock_pull_list.pot
  stock_pull_list/readme/CONTRIBUTORS.rst
  stock_pull_list/readme/DESCRIPTION.rst
  stock_pull_list/readme/ROADMAP.rst
  stock_pull_list/readme/USAGE.rst
  stock_pull_list/static/description/icon.png
  stock_pull_list/static/description/index.html
  stock_pull_list/tests/__init__.py
  stock_pull_list/tests/common.py
  stock_pull_list/tests/test_stock_pull_list.py
  stock_pull_list/wizards/__init__.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
  stock_pull_list/wizards/stock_pull_list_wizard.xml
Labels: 13.0

#471 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available_mrp/__manifest__.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: 12.0
