Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-06, with the labels that each got.

#523 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  sale_stock_available_info_popup/i18n/de.po
  sale_stock_info_popup/i18n/de.po
Labels: 12.0

#524 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/i18n/cs_CZ.po
  stock_inventory_discrepancy/i18n/de.po
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/es_ES.po
  stock_inventory_discrepancy/i18n/fr.po
  stock_inventory_discrepancy/i18n/fr_FR.po
  stock_inventory_discrepancy/i18n/hr.po
  stock_inventory_discrepancy/i18n/it.po
  stock_inventory_discrepancy/i18n/nl.po
  stock_inventory_discrepancy/i18n/nl_NL.po
  stock_inventory_discrepancy/i18n/pt_BR.po
  stock_inventory_discrepancy/i18n/sl.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/i18n/tr_TR.po
  stock_inventory_discrepancy/i18n/zh_CN.po
  stock_inventory_discrepancy/models/stock_inventory.py
  stock_inventory_discrepancy/models/stock_inventory_line.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_inventory_view.xml
Labels: 12.0

#526 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/i18n/cs_CZ.po
  stock_inventory_discrepancy/i18n/de.po
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/es_ES.po
  stock_inventory_discrepancy/i18n/fr.po
  stock_inventory_discrepancy/i18n/fr_FR.po
  stock_inventory_discrepancy/i18n/hr.po
  stock_inventory_discrepancy/i18n/it.po
  stock_inventory_discrepancy/i18n/nl.po
  stock_inventory_discrepancy/i18n/nl_NL.po
  stock_inventory_discrepancy/i18n/pt_BR.po
  stock_inventory_discrepancy/i18n/sl.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/i18n/tr_TR.po
  stock_inventory_discrepancy/i18n/zh_CN.po
  stock_inventory_discrepancy/models/stock_inventory.py
  stock_inventory_discrepancy/models/stock_inventory_line.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_inventory_view.xml
Labels: 13.0

#528 Updating from latest OCA 13.0
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/views/stock_move_view.xml
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/i18n/cs_CZ.po
  stock_inventory_discrepancy/i18n/de.po
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/es_ES.po
  stock_inventory_discrepancy/i18n/fr.po
  stock_inventory_discrepancy/i18n/fr_FR.po
  stock_inventory_discrepancy/i18n/hr.po
  stock_inventory_discrepancy/i18n/it.po
  stock_inventory_discrepancy/i18n/nl.po
  stock_inventory_discrepancy/i18n/nl_NL.po
  stock_inventory_discrepancy/i18n/pt_BR.po
  stock_inventory_discrepancy/i18n/sl.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/i18n/tr_TR.po
  stock_inventory_discrepancy/i18n/zh_CN.po
  stock_inventory_discrepancy/models/stock_inventory.py
  stock_inventory_discrepancy/models/stock_inventory_line.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_inventory_view.xml
  stock_request/i18n/es.po
Labels: 13.0.project_mi_465

#529 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_mts_mto_rule/README.rst
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/models/stock_rule.py
  stock_mts_mto_rule/readme/CONFIGURE.rst
  stock_mts_mto_rule/readme/CONTRIBUTORS.rst
  stock_mts_mto_rule/readme/DESCRIPTION.rst
  stock_mts_mto_rule/readme/ROADMAP.rst
  stock_mts_mto_rule/readme/USAGE.rst
  stock_mts_mto_rule/static/description/index.html
Labels: 12.0

#530 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/i18n/stock_packaging_calculator.pot
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/common.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
Labels: 13.0

#531 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_available_mrp/odoo/addons/stock_available_mrp
  setup/stock_available_mrp/setup.py
  stock_available_mrp/README.rst
  stock_available_mrp/__init__.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/demo/mrp_data.xml
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/DESCRIPTION.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/static/description/icon.png
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/__init__.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: 14.0

#532 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_account_inventory_discrepancy/odoo/addons/stock_account_inventory_discrepancy
  setup/stock_account_inventory_discrepancy/setup.py
  stock_account_inventory_discrepancy/README.rst
  stock_account_inventory_discrepancy/__init__.py
  stock_account_inventory_discrepancy/__manifest__.py
  stock_account_inventory_discrepancy/i18n/stock_account_inventory_discrepancy.pot
  stock_account_inventory_discrepancy/models/__init__.py
  stock_account_inventory_discrepancy/models/stock_inventory_line.py
  stock_account_inventory_discrepancy/models/stock_location.py
  stock_account_inventory_discrepancy/models/stock_warehouse.py
  stock_account_inventory_discrepancy/readme/CONFIGURE.rst
  stock_account_inventory_discrepancy/readme/CONTRIBUTORS.rst
  stock_account_inventory_discrepancy/readme/DESCRIPTION.rst
  stock_account_inventory_discrepancy/static/description/icon.png
  stock_account_inventory_discrepancy/static/description/index.html
  stock_account_inventory_discrepancy/tests/__init__.py
  stock_account_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_account_inventory_discrepancy/views/stock_inventory_view.xml
  stock_account_inventory_discrepancy/views/stock_location_view.xml
  stock_account_inventory_discrepancy/views/stock_warehouse_view.xml
Labels: 12.0

#533 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_cycle_count/__manifest__.py
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/reports/report_stock_location_accuracy.py
  stock_cycle_count/tests/test_stock_cycle_count.py
Labels: 13.0

#534 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/product_product.py
Labels: 14.0

#536 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_packaging_calculator_packaging_type/odoo/addons/stock_packaging_calculator_packaging_type
  setup/stock_packaging_calculator_packaging_type/setup.py
  setup/stock_product_qty_by_packaging/odoo/addons/stock_product_qty_by_packaging
  setup/stock_product_qty_by_packaging/setup.py
  setup/stock_vertical_lift_qty_by_packaging/odoo/addons/stock_vertical_lift_qty_by_packaging
  setup/stock_vertical_lift_qty_by_packaging/setup.py
  stock_packaging_calculator_packaging_type/README.rst
  stock_packaging_calculator_packaging_type/__init__.py
  stock_packaging_calculator_packaging_type/__manifest__.py
  stock_packaging_calculator_packaging_type/i18n/stock_packaging_calculator_packaging_type.pot
  stock_packaging_calculator_packaging_type/models/__init__.py
  stock_packaging_calculator_packaging_type/models/product.py
  stock_packaging_calculator_packaging_type/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator_packaging_type/readme/CONTRIBUTORS.rst
  stock_packaging_calculator_packaging_type/readme/DESCRIPTION.rst
  stock_packaging_calculator_packaging_type/static/description/icon.png
  stock_packaging_calculator_packaging_type/static/description/index.html
  stock_packaging_calculator_packaging_type/tests/__init__.py
  stock_packaging_calculator_packaging_type/tests/test_packaging_by_qty.py
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/__init__.py
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/i18n/stock_product_qty_by_packaging.pot
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_move.py
  stock_product_qty_by_packaging/models/stock_move_line.py
  stock_product_qty_by_packaging/models/stock_quant.py
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/static/description/icon.png
  stock_product_qty_by_packaging/static/description/index.html
  stock_product_qty_by_packaging/tests/__init__.py
  stock_product_qty_by_packaging/tests/test_stock.py
  stock_product_qty_by_packaging/views/stock_picking.xml
  stock_vertical_lift_kardex/proxy/README.rst
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
  stock_vertical_lift_qty_by_packaging/README.rst
  stock_vertical_lift_qty_by_packaging/__init__.py
  stock_vertical_lift_qty_by_packaging/__manifest__.py
  stock_vertical_lift_qty_by_packaging/i18n/stock_vertical_lift_qty_by_packaging.pot
  stock_vertical_lift_qty_by_packaging/models/__init__.py
  stock_vertical_lift_qty_by_packaging/models/vertical_lift_operation_base.py
  stock_vertical_lift_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_vertical_lift_qty_by_packaging/readme/DESCRIPTION.rst
  stock_vertical_lift_qty_by_packaging/static/description/icon.png
  stock_vertical_lift_qty_by_packaging/static/description/index.html
  stock_vertical_lift_qty_by_packaging/views/vertical_lift_operation_base_views.xml
Labels: 13.0

#537 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request/__manifest__.py
  stock_request/security/stock_request_security.xml
Labels: 13.0

#538 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_cancel_confirm/odoo/addons/stock_picking_cancel_confirm
  setup/stock_picking_cancel_confirm/setup.py
  stock_picking_cancel_confirm/README.rst
  stock_picking_cancel_confirm/__init__.py
  stock_picking_cancel_confirm/__manifest__.py
  stock_picking_cancel_confirm/i18n/stock_picking_cancel_confirm.pot
  stock_picking_cancel_confirm/models/__init__.py
  stock_picking_cancel_confirm/models/stock_picking.py
  stock_picking_cancel_confirm/readme/CONTRIBUTORS.rst
  stock_picking_cancel_confirm/readme/DESCRIPTION.rst
  stock_picking_cancel_confirm/static/description/icon.png
  stock_picking_cancel_confirm/static/description/index.html
  stock_request/i18n/ca.po
  stock_request/i18n/de.po
  stock_request/i18n/el_GR.po
  stock_request/i18n/es.po
  stock_request/i18n/es_ES.po
  stock_request/i18n/eu.po
  stock_request/i18n/fi.po
  stock_request/i18n/fr.po
  stock_request/i18n/fr_CH.po
  stock_request/i18n/fr_FR.po
  stock_request/i18n/gl.po
  stock_request/i18n/hr.po
  stock_request/i18n/hr_HR.po
  stock_request/i18n/it.po
  stock_request/i18n/nl.po
  stock_request/i18n/nl_NL.po
  stock_request/i18n/pt.po
  stock_request/i18n/pt_BR.po
  stock_request/i18n/ro.po
  stock_request/i18n/ru.po
  stock_request/i18n/sl.po
  stock_request/i18n/stock_request.pot
  stock_request/i18n/tr.po
  stock_request/i18n/tr_TR.po
  stock_request/i18n/vi_VN.po
  stock_request/i18n/zh_CN.po
Labels: 14.0

#540 Backmerge from 12.0 into 12.0.project_MI_465
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_account_inventory_discrepancy/odoo/addons/stock_account_inventory_discrepancy
  setup/stock_account_inventory_discrepancy/setup.py
  stock_account_inventory_discrepancy/README.rst
  stock_account_inventory_discrepancy/__init__.py
  stock_account_inventory_discrepancy/__manifest__.py
  stock_account_inventory_discrepancy/i18n/stock_account_inventory_discrepancy.pot
  stock_account_inventory_discrepancy/models/__init__.py
  stock_account_inventory_discrepancy/models/stock_inventory_line.py
  stock_account_inventory_discrepancy/models/stock_location.py
  stock_account_inventory_discrepancy/models/stock_warehouse.py
  stock_account_inventory_discrepancy/readme/CONFIGURE.rst
  stock_account_inventory_discrepancy/readme/CONTRIBUTORS.rst
  stock_account_inventory_discrepancy/readme/DESCRIPTION.rst
  stock_account_inventory_discrepancy/static/description/icon.png
  stock_account_inventory_discrepancy/static/description/index.html
  stock_account_inventory_discrepancy/tests/__init__.py
  stock_account_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_account_inventory_discrepancy/views/stock_inventory_view.xml
  stock_account_inventory_discrepancy/views/stock_location_view.xml
  stock_account_inventory_discrepancy/views/stock_warehouse_view.xml
  stock_mts_mto_rule/README.rst
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/models/stock_rule.py
  stock_mts_mto_rule/readme/CONFIGURE.rst
  stock_mts_mto_rule/readme/CONTRIBUTORS.rst
  stock_mts_mto_rule/readme/DESCRIPTION.rst
  stock_mts_mto_rule/readme/ROADMAP.rst
  stock_mts_mto_rule/readme/USAGE.rst
  stock_mts_mto_rule/static/description/index.html
Labels: 12.0.project_mi_465

#541 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_move_location/__manifest__.py
  stock_move_location/tests/test_common.py
Labels: 13.0

#542 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request/__manifest__.py
  stock_request/migrations/13.0.1.0.0/noupdate_changes.xml
  stock_request/migrations/13.0.1.0.0/post-migration.py
  stock_request/security/stock_request_security.xml
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/security/stock_reserve_rule_security.xml
Labels: 13.0

#543 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_change_qty_reason/i18n/es.po
Labels: 12.0

#544 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/views/stock_picking_views.xml
Labels: 13.0
