Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-05, with the labels that each got.

#509 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_account_inventory_force_date/__manifest__.py
  stock_account_inventory_force_date/models/stock_inventory.py
Labels: 12.0

#510 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_cubiscan/__manifest__.py
  stock_cubiscan/wizard/cubiscan_wizard.py
Labels: 13.0

#511 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_position/odoo/addons/stock_location_position
  setup/stock_location_position/setup.py
  stock_location_position/README.rst
  stock_location_position/__init__.py
  stock_location_position/__manifest__.py
  stock_location_position/i18n/stock_location_position.pot
  stock_location_position/models/__init__.py
  stock_location_position/models/stock_location.py
  stock_location_position/readme/CONTRIBUTORS.rst
  stock_location_position/readme/CREDITS.rst
  stock_location_position/readme/DESCRIPTION.rst
  stock_location_position/static/description/icon.png
  stock_location_position/static/description/index.html
  stock_location_position/views/stock_location.xml
Labels: 14.0

#512 Update 20210510 - stock-logistics-warehouse - OCA 12.0
  stock_account_inventory_force_date/__manifest__.py
  stock_account_inventory_force_date/models/stock_inventory.py
Labels: 12.0.project_mi_465

#513 Update 20210510 - stock-logistics-warehouse - OCA 13.0
  stock_cubiscan/__manifest__.py
  stock_cubiscan/wizard/cubiscan_wizard.py
Labels: 13.0.project_mi_465

#514 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_measuring_device/__manifest__.py
  stock_measuring_device/i18n/stock_measuring_device.pot
  stock_measuring_device/models/measuring_device.py
  stock_measuring_device/models/product_packaging.py
  stock_measuring_device/static/src/js/measuring_wizard.js
  stock_measuring_device/views/assets.xml
  stock_measuring_device/wizard/measuring_wizard.py
  stock_measuring_device/wizard/measuring_wizard.xml
  stock_measuring_device/wizard/measuring_wizard_line.py
  stock_measuring_device_zippcube/__manifest__.py
  stock_measuring_device_zippcube/components/zippcube_device_component.py
  stock_measuring_device_zippcube/i18n/stock_measuring_device_zippcube.pot
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/utils.py
Labels: 13.0

#515 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  scrap_reason_code/i18n/fr.po
Labels: 14.0

#516 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  .copier-answers.yml
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
Labels: 14.0

#517 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_lot_filter_available/odoo/addons/stock_lot_filter_available
  setup/stock_lot_filter_available/setup.py
  stock_lot_filter_available/README.rst
  stock_lot_filter_available/__init__.py
  stock_lot_filter_available/__manifest__.py
  stock_lot_filter_available/i18n/es.po
  stock_lot_filter_available/i18n/stock_lot_filter_available.pot
  stock_lot_filter_available/models/__init__.py
  stock_lot_filter_available/models/stock_production_lot.py
  stock_lot_filter_available/readme/CONTRIBUTORS.rst
  stock_lot_filter_available/readme/DESCRIPTION.rst
  stock_lot_filter_available/readme/USAGE.rst
  stock_lot_filter_available/static/description/icon.png
  stock_lot_filter_available/static/description/index.html
  stock_lot_filter_available/tests/__init__.py
  stock_lot_filter_available/tests/test_stock_lot_filter_available.py
  stock_lot_filter_available/views/stock_production_lot_views.xml
Labels: 13.0

#518 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_available_mrp/odoo/addons/stock_available_mrp
  setup/stock_available_mrp/setup.py
  stock_available_mrp/README.rst
  stock_available_mrp/__init__.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/demo/mrp_data.xml
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/DESCRIPTION.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/static/description/icon.png
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/__init__.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: 13.0

#519 Update 20210524 - stock-logistics-warehouse - OCA 13.0
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_available_mrp/odoo/addons/stock_available_mrp
  setup/stock_available_mrp/setup.py
  setup/stock_lot_filter_available/odoo/addons/stock_lot_filter_available
  setup/stock_lot_filter_available/setup.py
  stock_available_mrp/README.rst
  stock_available_mrp/__init__.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/demo/mrp_data.xml
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/DESCRIPTION.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/static/description/icon.png
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/__init__.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_lot_filter_available/README.rst
  stock_lot_filter_available/__init__.py
  stock_lot_filter_available/__manifest__.py
  stock_lot_filter_available/i18n/es.po
  stock_lot_filter_available/i18n/stock_lot_filter_available.pot
  stock_lot_filter_available/models/__init__.py
  stock_lot_filter_available/models/stock_production_lot.py
  stock_lot_filter_available/readme/CONTRIBUTORS.rst
  stock_lot_filter_available/readme/DESCRIPTION.rst
  stock_lot_filter_available/readme/USAGE.rst
  stock_lot_filter_available/static/description/icon.png
  stock_lot_filter_available/static/description/index.html
  stock_lot_filter_available/tests/__init__.py
  stock_lot_filter_available/tests/test_stock_lot_filter_available.py
  stock_lot_filter_available/views/stock_production_lot_views.xml
  stock_measuring_device/__manifest__.py
  stock_measuring_device/i18n/stock_measuring_device.pot
  stock_measuring_device/models/measuring_device.py
  stock_measuring_device/models/product_packaging.py
  stock_measuring_device/static/src/js/measuring_wizard.js
  stock_measuring_device/views/assets.xml
  stock_measuring_device/wizard/measuring_wizard.py
  stock_measuring_device/wizard/measuring_wizard.xml
  stock_measuring_device/wizard/measuring_wizard_line.py
  stock_measuring_device_zippcube/__manifest__.py
  stock_measuring_device_zippcube/components/zippcube_device_component.py
  stock_measuring_device_zippcube/i18n/stock_measuring_device_zippcube.pot
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/utils.py
Labels: 13.0.project_mi_465

#520 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/views/stock_move_view.xml
Labels: 13.0

#521 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request/i18n/es.po
Labels: 13.0

#522 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_request/i18n/es.po
Labels: 14.0
