Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-12, with the labels that each got.

#663 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request/__manifest__.py
  stock_request/models/stock_request.py
Labels: 13.0

#664 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_inventory_preparation_filter_pos/odoo/addons/stock_inventory_preparation_filter_pos
  setup/stock_inventory_preparation_filter_pos/setup.py
  stock_inventory_preparation_filter/models/stock_inventory.py
  stock_inventory_preparation_filter/views/stock_inventory_view.xml
  stock_inventory_preparation_filter_pos/README.rst
  stock_inventory_preparation_filter_pos/__init__.py
  stock_inventory_preparation_filter_pos/__manifest__.py
  stock_inventory_preparation_filter_pos/i18n/stock_inventory_preparation_filter_pos.pot
  stock_inventory_preparation_filter_pos/models/__init__.py
  stock_inventory_preparation_filter_pos/models/stock_inventory.py
  stock_inventory_preparation_filter_pos/readme/CONTRIBUTORS.rst
  stock_inventory_preparation_filter_pos/readme/DESCRIPTION.rst
  stock_inventory_preparation_filter_pos/readme/USAGE.rst
  stock_inventory_preparation_filter_pos/static/description/icon.png
  stock_inventory_preparation_filter_pos/static/description/index.html
  stock_inventory_preparation_filter_pos/tests/__init__.py
  stock_inventory_preparation_filter_pos/tests/test_preparation_filter_pos.py
  stock_inventory_preparation_filter_pos/views/stock_inventory.xml
  stock_orderpoint_manual_procurement/__manifest__.py
  stock_orderpoint_manual_procurement/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement/tests/test_stock_orderpoint_manual_procurement.py
  stock_vertical_lift_kardex/__manifest__.py
  stock_vertical_lift_kardex/proxy/README.rst
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
Labels: 14.0

#665 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_orderpoint_generator/i18n/it.po
Labels: 12.0

#666 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_quant_view_reservation/odoo/addons/stock_quant_view_reservation
  setup/stock_quant_view_reservation/setup.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_quant_view_reservation/README.rst
  stock_quant_view_reservation/__init__.py
  stock_quant_view_reservation/__manifest__.py
  stock_quant_view_reservation/i18n/stock_quant_view_reservation.pot
  stock_quant_view_reservation/models/__init__.py
  stock_quant_view_reservation/models/stock_quant.py
  stock_quant_view_reservation/readme/CONTRIBUTORS.rst
  stock_quant_view_reservation/readme/DESCRIPTION.rst
  stock_quant_view_reservation/readme/USAGE.rst
  stock_quant_view_reservation/static/description/icon.png
  stock_quant_view_reservation/static/description/index.html
  stock_quant_view_reservation/views/stock_move_line_views.xml
  stock_quant_view_reservation/views/stock_quant.xml
Labels: 13.0

#667 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/models/vertical_lift_operation_put.py
  stock_vertical_lift/tests/test_inventory.py
  stock_vertical_lift/tests/test_pick.py
  stock_vertical_lift/wizards/vertical_lift_shuttle_manual_barcode.py
Labels: 14.0

#668 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_quant_expiration_date_tree/odoo/addons/stock_quant_expiration_date_tree
  setup/stock_quant_expiration_date_tree/setup.py
  stock_quant_expiration_date_tree/README.rst
  stock_quant_expiration_date_tree/__init__.py
  stock_quant_expiration_date_tree/__manifest__.py
  stock_quant_expiration_date_tree/i18n/es.po
  stock_quant_expiration_date_tree/i18n/stock_quant_expiration_date_tree.pot
  stock_quant_expiration_date_tree/models/__init__.py
  stock_quant_expiration_date_tree/models/stock_quant.py
  stock_quant_expiration_date_tree/readme/CONTRIBUTORS.rst
  stock_quant_expiration_date_tree/readme/DESCRIPTION.rst
  stock_quant_expiration_date_tree/static/description/icon.png
  stock_quant_expiration_date_tree/static/description/index.html
  stock_quant_expiration_date_tree/views/stock_quant.xml
Labels: 13.0

#669 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_location_tray/__manifest__.py
  stock_location_tray/models/stock_location.py
Labels: 14.0

#670 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_available/__manifest__.py
  stock_available/models/product_product.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: 14.0

#671 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_location_tray/__manifest__.py
  stock_location_tray/models/stock_location.py
  stock_location_tray/models/stock_location_tray_type.py
Labels: 14.0

#672 Merging 13.0 into 13.0.project_MI_465
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_quant_expiration_date_tree/odoo/addons/stock_quant_expiration_date_tree
  setup/stock_quant_expiration_date_tree/setup.py
  setup/stock_quant_view_reservation/odoo/addons/stock_quant_view_reservation
  setup/stock_quant_view_reservation/setup.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_quant_expiration_date_tree/README.rst
  stock_quant_expiration_date_tree/__init__.py
  stock_quant_expiration_date_tree/__manifest__.py
  stock_quant_expiration_date_tree/i18n/es.po
  stock_quant_expiration_date_tree/i18n/stock_quant_expiration_date_tree.pot
  stock_quant_expiration_date_tree/models/__init__.py
  stock_quant_expiration_date_tree/models/stock_quant.py
  stock_quant_expiration_date_tree/readme/CONTRIBUTORS.rst
  stock_quant_expiration_date_tree/readme/DESCRIPTION.rst
  stock_quant_expiration_date_tree/static/description/icon.png
  stock_quant_expiration_date_tree/static/description/index.html
  stock_quant_expiration_date_tree/views/stock_quant.xml
  stock_quant_view_reservation/README.rst
  stock_quant_view_reservation/__init__.py
  stock_quant_view_reservation/__manifest__.py
  stock_quant_view_reservation/i18n/stock_quant_view_reservation.pot
  stock_quant_view_reservation/models/__init__.py
  stock_quant_view_reservation/models/stock_quant.py
  stock_quant_view_reservation/readme/CONTRIBUTORS.rst
  stock_quant_view_reservation/readme/DESCRIPTION.rst
  stock_quant_view_reservation/readme/USAGE.rst
  stock_quant_view_reservation/static/description/icon.png
  stock_quant_view_reservation/static/description/index.html
  stock_quant_view_reservation/views/stock_move_line_views.xml
  stock_quant_view_reservation/views/stock_quant.xml
  stock_request/__manifest__.py
  stock_request/models/stock_request.py
Labels: 13.0.project_mi_465

#673 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_cycle_count/__manifest__.py
  stock_cycle_count/models/stock_cycle_count.py
  stock_cycle_count/models/stock_location.py
  stock_move_location/__manifest__.py
  stock_move_location/models/stock_picking_type.py
  stock_move_location/wizard/stock_move_location.py
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_move_link/models/stock_warehouse_orderpoint.py
  stock_request/__manifest__.py
  stock_request/models/stock_picking.py
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/models/vertical_lift_shuttle.py
Labels: 14.0

#675 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_move_link/models/stock.py
Labels: 14.0

#676 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_cycle_count/__manifest__.py
  stock_cycle_count/models/stock_inventory.py
  stock_warehouse_calendar/README.rst
  stock_warehouse_calendar/__manifest__.py
  stock_warehouse_calendar/static/description/index.html
Labels: 14.0

#677 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_package_grouped/odoo/addons/stock_picking_package_grouped
  setup/stock_picking_package_grouped/setup.py
  stock_picking_package_grouped/README.rst
  stock_picking_package_grouped/__init__.py
  stock_picking_package_grouped/__manifest__.py
  stock_picking_package_grouped/i18n/es.po
  stock_picking_package_grouped/i18n/stock_picking_package_grouped.pot
  stock_picking_package_grouped/models/__init__.py
  stock_picking_package_grouped/models/stock_picking.py
  stock_picking_package_grouped/models/stock_picking_type.py
  stock_picking_package_grouped/readme/CONFIGURE.rst
  stock_picking_package_grouped/readme/CONTRIBUTORS.rst
  stock_picking_package_grouped/readme/DESCRIPTION.rst
  stock_picking_package_grouped/readme/USAGE.rst
  stock_picking_package_grouped/static/description/icon.png
  stock_picking_package_grouped/static/description/index.html
  stock_picking_package_grouped/tests/__init__.py
  stock_picking_package_grouped/tests/test_stock_picking_package_grouped.py
  stock_picking_package_grouped/views/stock_picking_type_views.xml
Labels: 13.0

#678 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_helper/odoo/addons/stock_helper
  setup/stock_helper/setup.py
  stock_helper/README.rst
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/i18n/stock_helper.pot
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/readme/DESCRIPTION.rst
  stock_helper/static/description/icon.png
  stock_helper/static/description/index.html
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
Labels: 15.0

#679 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_reserve_rule/README.rst
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/readme/CONTRIBUTORS.rst
  stock_reserve_rule/static/description/index.html
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: 14.0

#680 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_inventory_line_product_cost/i18n/fr.po
  stock_inventory_line_product_cost/i18n/fr_FR.po
Labels: 14.0
