Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2021-07, with the labels that each got.

#545 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  sale_stock_info_popup/i18n/it.po
Labels: 12.0

#546 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_request_picking_type/odoo/addons/stock_request_picking_type
  setup/stock_request_picking_type/setup.py
  stock_request_picking_type/README.rst
  stock_request_picking_type/__init__.py
  stock_request_picking_type/__manifest__.py
  stock_request_picking_type/data/stock_picking_type.xml
  stock_request_picking_type/i18n/es.po
  stock_request_picking_type/i18n/pt_BR.po
  stock_request_picking_type/i18n/stock_request_picking_type.pot
  stock_request_picking_type/i18n/zh_CN.po
  stock_request_picking_type/migrations/12.0.2.0.0/post-migration.py
  stock_request_picking_type/models/__init__.py
  stock_request_picking_type/models/stock_picking_type.py
  stock_request_picking_type/models/stock_request_order.py
  stock_request_picking_type/readme/CONTRIBUTORS.rst
  stock_request_picking_type/readme/DESCRIPTION.rst
  stock_request_picking_type/readme/USAGE.rst
  stock_request_picking_type/static/description/icon.png
  stock_request_picking_type/static/description/index.html
  stock_request_picking_type/tests/__init__.py
  stock_request_picking_type/tests/test_stock_picking_type.py
  stock_request_picking_type/tests/test_stock_request.py
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_order_views.xml
Labels: 14.0

#547 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_request_picking_type/__manifest__.py
  stock_request_picking_type/i18n/es.po
  stock_request_picking_type/i18n/pt_BR.po
  stock_request_picking_type/i18n/stock_request_picking_type.pot
  stock_request_picking_type/i18n/zh_CN.po
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_order_views.xml
Labels: 13.0

#548 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_search_supplierinfo_code/odoo/addons/stock_search_supplierinfo_code
  setup/stock_search_supplierinfo_code/setup.py
  stock_search_supplierinfo_code/README.rst
  stock_search_supplierinfo_code/__init__.py
  stock_search_supplierinfo_code/__manifest__.py
  stock_search_supplierinfo_code/i18n/stock_search_supplierinfo_code.pot
  stock_search_supplierinfo_code/readme/CONTRIBUTORS.rst
  stock_search_supplierinfo_code/readme/DESCRIPTION.rst
  stock_search_supplierinfo_code/static/description/icon.png
  stock_search_supplierinfo_code/static/description/index.html
  stock_search_supplierinfo_code/views/stock_picking.xml
Labels: 14.0

#549 Updating from latest OCA 12.0
  sale_stock_info_popup/i18n/it.po
  stock_change_qty_reason/i18n/es.po
Labels: 12.0.project_mi_465

#550 Updating from latest OCA 13.0
  stock_move_location/__manifest__.py
  stock_move_location/tests/test_common.py
  stock_request/__manifest__.py
  stock_request/migrations/13.0.1.0.0/noupdate_changes.xml
  stock_request/migrations/13.0.1.0.0/post-migration.py
  stock_request/security/stock_request_security.xml
  stock_request_picking_type/__manifest__.py
  stock_request_picking_type/i18n/es.po
  stock_request_picking_type/i18n/pt_BR.po
  stock_request_picking_type/i18n/stock_request_picking_type.pot
  stock_request_picking_type/i18n/zh_CN.po
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_order_views.xml
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/security/stock_reserve_rule_security.xml
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/views/stock_picking_views.xml
Labels: 13.0.project_mi_465

#551 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_change_qty_reason/__manifest__.py
  stock_change_qty_reason/models/stock_inventory.py
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
  stock_packaging_calculator_packaging_type/__manifest__.py
  stock_packaging_calculator_packaging_type/tests/test_packaging_by_qty.py
Labels: 13.0

#552 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/models/quant.py
Labels: 12.0

#553 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_inventory_include_exhausted/__manifest__.py
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
Labels: 13.0

#554 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  sale_stock_available_info_popup/i18n/it.po
Labels: 12.0

#555 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 12.0

#556 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 13.0

#557 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/tests/utils.py
Labels: 13.0

#558 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_move_packaging_qty/odoo/addons/stock_move_packaging_qty
  setup/stock_move_packaging_qty/setup.py
  stock_move_packaging_qty/README.rst
  stock_move_packaging_qty/__init__.py
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/i18n/stock_move_packaging_qty.pot
  stock_move_packaging_qty/models/__init__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_move_packaging_qty/readme/CONTRIBUTORS.rst
  stock_move_packaging_qty/readme/DESCRIPTION.rst
  stock_move_packaging_qty/static/description/icon.png
  stock_move_packaging_qty/static/description/index.html
  stock_move_packaging_qty/tests/__init__.py
  stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
  stock_move_packaging_qty/views/stock_move_tree_view.xml
  stock_move_packaging_qty/views/stock_picking_form_view.xml
Labels: 12.0

#559 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_orderpoint_move_link/odoo/addons/stock_orderpoint_move_link
  setup/stock_orderpoint_move_link/setup.py
  stock_orderpoint_move_link/README.rst
  stock_orderpoint_move_link/__init__.py
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_move_link/i18n/stock_orderpoint_move_link.pot
  stock_orderpoint_move_link/i18n/zh_CN.po
  stock_orderpoint_move_link/models/__init__.py
  stock_orderpoint_move_link/models/stock.py
  stock_orderpoint_move_link/models/stock_move.py
  stock_orderpoint_move_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_move_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_move_link/readme/DESCRIPTION.rst
  stock_orderpoint_move_link/static/description/icon.png
  stock_orderpoint_move_link/static/description/index.html
  stock_orderpoint_move_link/tests/__init__.py
  stock_orderpoint_move_link/tests/test_stock_orderpoint_move_link.py
  stock_orderpoint_move_link/views/stock_move_views.xml
Labels: 14.0

#560 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  sale_stock_available_info_popup/i18n/pt.po
  sale_stock_info_popup/i18n/pt.po
Labels: 12.0

#561 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  sale_stock_available_info_popup/i18n/it.po
  sale_stock_info_popup/i18n/it.po
  stock_available/i18n/pt.po
  stock_available_unreserved/i18n/pt.po
  stock_secondary_unit/README.rst
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: 12.0

#562 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_move_packaging_qty/odoo/addons/stock_move_packaging_qty
  setup/stock_move_packaging_qty/setup.py
  stock_move_packaging_qty/README.rst
  stock_move_packaging_qty/__init__.py
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/i18n/stock_move_packaging_qty.pot
  stock_move_packaging_qty/models/__init__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_move_packaging_qty/readme/CONTRIBUTORS.rst
  stock_move_packaging_qty/readme/DESCRIPTION.rst
  stock_move_packaging_qty/static/description/icon.png
  stock_move_packaging_qty/static/description/index.html
  stock_move_packaging_qty/tests/__init__.py
  stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
  stock_move_packaging_qty/views/stock_move_tree_view.xml
  stock_move_packaging_qty/views/stock_picking_form_view.xml
Labels: 13.0

#564 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_quant_manual_assign/__init__.py
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/i18n/stock_quant_manual_assign.pot
  stock_quant_manual_assign/models/__init__.py
  stock_quant_manual_assign/models/stock_picking_type.py
  stock_quant_manual_assign/readme/CONFIGURATION.rst
  stock_quant_manual_assign/tests/test_stock_quant_manual_assign.py
  stock_quant_manual_assign/views/stock_picking_type_views.xml
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: 14.0

#566 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/i18n/stock_product_qty_by_packaging.pot
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_inventory_line.py
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/static/description/index.html
  stock_product_qty_by_packaging/views/stock_inventory_line.xml
Labels: 13.0
