Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2022-06, with the labels that each got.

#738 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/hooks.py
Labels: 12.0

#739 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_request_direction/odoo/addons/stock_request_direction
  setup/stock_request_direction/setup.py
  stock_request_direction/README.rst
  stock_request_direction/__init__.py
  stock_request_direction/__manifest__.py
  stock_request_direction/i18n/es.po
  stock_request_direction/i18n/stock_request_direction.pot
  stock_request_direction/i18n/zh_CN.po
  stock_request_direction/models/__init__.py
  stock_request_direction/models/stock_request.py
  stock_request_direction/models/stock_request_order.py
  stock_request_direction/readme/CONTRIBUTORS.rst
  stock_request_direction/readme/DESCRIPTION.rst
  stock_request_direction/readme/USAGE.rst
  stock_request_direction/static/description/icon.png
  stock_request_direction/static/description/index.html
  stock_request_direction/tests/__init__.py
  stock_request_direction/tests/test_stock_request_direction.py
  stock_request_direction/views/res_config_settings.xml
  stock_request_direction/views/stock_request_order_views.xml
  stock_request_direction/views/stock_request_views.xml
  stock_request_picking_type/tests/test_stock_request.py
Labels: 14.0

#741 13.0.project mi 465.update 20220606
  setup/stock_available_sale/odoo/addons/stock_available_sale
  setup/stock_available_sale/setup.py
  stock_available_sale/__manifest__.py
Labels: bug, 13.0.project_mi_465

#742 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_location_empty/i18n/de.po
  stock_secondary_unit/i18n/de.po
Labels: 14.0

#743 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_available/i18n/es.po
Labels: 13.0

#744 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_inventory_line_open/odoo/addons/stock_inventory_line_open
  setup/stock_inventory_line_open/setup.py
  stock_inventory_line_open/README.rst
  stock_inventory_line_open/__init__.py
  stock_inventory_line_open/__manifest__.py
  stock_inventory_line_open/i18n/stock_inventory_line_open.pot
  stock_inventory_line_open/models/__init__.py
  stock_inventory_line_open/models/stock_inventory.py
  stock_inventory_line_open/readme/CONTRIBUTORS.rst
  stock_inventory_line_open/readme/DESCRIPTION.rst
  stock_inventory_line_open/static/description/icon.png
  stock_inventory_line_open/static/description/index.html
  stock_inventory_line_open/views/stock_inventory_view.xml
Labels: 14.0

#746 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  setup/_metapackage/VERSION.txt
Labels: 13.0

#747 Backmerging 13.0 into 13.0.project_MI_465
  setup/_metapackage/VERSION.txt
  stock_available/i18n/es.po
Labels: 13.0.project_mi_465

#748 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request/__manifest__.py
Labels: 12.0

#749 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  stock_change_qty_reason/__manifest__.py
  stock_change_qty_reason/i18n/stock_change_qty_reason.pot
  stock_change_qty_reason/models/stock_inventory_line_reason.py
  stock_change_qty_reason/security/stock_security.xml
  stock_change_qty_reason/views/stock_inventory_line_reason_view.xml
  stock_change_qty_reason/views/stock_inventory_line_view.xml
  stock_change_qty_reason/views/stock_inventory_view.xml
Labels: 13.0

#750 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: 14.0

#751 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: 15.0

#752 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_inventory_chatter/i18n/sl.po
  stock_inventory_virtual_location/i18n/sl.po
Labels: 12.0

#753 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_available_unreserved/i18n/sl.po
Labels: 12.0

#754 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_show_linked/odoo/addons/stock_picking_show_linked
  setup/stock_picking_show_linked/setup.py
  stock_picking_show_linked/README.rst
  stock_picking_show_linked/__init__.py
  stock_picking_show_linked/__manifest__.py
  stock_picking_show_linked/i18n/stock_picking_show_linked.pot
  stock_picking_show_linked/models/__init__.py
  stock_picking_show_linked/models/stock_picking.py
  stock_picking_show_linked/readme/CONTRIBUTORS.rst
  stock_picking_show_linked/readme/DESCRIPTION.rst
  stock_picking_show_linked/static/description/icon.png
  stock_picking_show_linked/static/description/index.html
  stock_picking_show_linked/views/stock_picking.xml
Labels: 14.0

#755 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/models/sale_order.py
  sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
Labels: 13.0

#756 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_secondary_unit/odoo/addons/stock_secondary_unit
  setup/stock_secondary_unit/setup.py
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/i18n/zh_CN.po
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/readme/DESCRIPTION.rst
  stock_secondary_unit/readme/USAGE.rst
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: 15.0
