Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2022-03, with the labels that each got.

#712 Updating from latest OCA 13.0
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_inventory_include_exhausted/__manifest__.py
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
  stock_inventory_preparation_filter/README.rst
  stock_inventory_preparation_filter/__manifest__.py
  stock_inventory_preparation_filter/models/stock_inventory.py
  stock_inventory_preparation_filter/readme/CONTRIBUTORS.rst
  stock_inventory_preparation_filter/static/description/index.html
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/product.py
Labels: 13.0.project_mi_465

#714 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: 14.0

#715 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: 15.0

#716 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/views/product_view.xml
Labels: 14.0

#717 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  scrap_reason_code/README.rst
  scrap_reason_code/__init__.py
  scrap_reason_code/__manifest__.py
  scrap_reason_code/i18n/scrap_reason_code.pot
  scrap_reason_code/models/__init__.py
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_move.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONFIGURE.rst
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/readme/CREDITS.rst
  scrap_reason_code/readme/DESCRIPTION.rst
  scrap_reason_code/readme/ROADMAP.rst
  scrap_reason_code/readme/USAGE.rst
  scrap_reason_code/security/ir.model.access.csv
  scrap_reason_code/static/description/icon.png
  scrap_reason_code/static/description/index.html
  scrap_reason_code/tests/__init__.py
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_move_views.xml
  scrap_reason_code/views/stock_scrap_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/scrap_reason_code/odoo/addons/scrap_reason_code
  setup/scrap_reason_code/setup.py
Labels: 12.0

#718 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_lockdown/odoo/addons/stock_location_lockdown
  setup/stock_location_lockdown/setup.py
  stock_location_lockdown/README.rst
  stock_location_lockdown/__init__.py
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/pt.po
  stock_location_lockdown/i18n/stock_location_lockdown.pot
  stock_location_lockdown/i18n/zh_CN.po
  stock_location_lockdown/models/__init__.py
  stock_location_lockdown/models/stock_location.py
  stock_location_lockdown/models/stock_quant.py
  stock_location_lockdown/readme/CONTRIBUTORS.rst
  stock_location_lockdown/readme/DESCRIPTION.rst
  stock_location_lockdown/readme/USAGE.rst
  stock_location_lockdown/static/description/icon.png
  stock_location_lockdown/static/description/index.html
  stock_location_lockdown/tests/__init__.py
  stock_location_lockdown/tests/test_block_stock_location_entrance.py
  stock_location_lockdown/views/stock_location.xml
Labels: 15.0

#719 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  scrap_location_filter/README.rst
  scrap_location_filter/__init__.py
  scrap_location_filter/__manifest__.py
  scrap_location_filter/i18n/scrap_location_filter.pot
  scrap_location_filter/models/__init__.py
  scrap_location_filter/models/stock_location.py
  scrap_location_filter/models/stock_scrap.py
  scrap_location_filter/readme/CONTRIBUTORS.rst
  scrap_location_filter/readme/CREDITS.rst
  scrap_location_filter/readme/DESCRIPTION.rst
  scrap_location_filter/readme/USAGE.rst
  scrap_location_filter/static/description/icon.png
  scrap_location_filter/static/description/index.html
  scrap_location_filter/tests/__init__.py
  scrap_location_filter/tests/test_scrap_location_filter.py
  scrap_location_filter/views/stock_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/scrap_location_filter/odoo/addons/scrap_location_filter
  setup/scrap_location_filter/setup.py
  stock_orderpoint_origin/__manifest__.py
  stock_orderpoint_origin/models/procurement_group.py
Labels: 14.0

#720 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  scrap_reason_code/i18n/es.po
Labels: 14.0

#721 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_account_inventory_force_date/__manifest__.py
  stock_account_inventory_force_date/models/stock_inventory.py
Labels: 12.0

#722 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_quant_manual_assign/i18n/ca.po
  stock_quant_manual_assign/i18n/es.po
Labels: 13.0
