Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2022-07, with the labels that each got.

#758 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: 13.0

#759 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: 14.0

#760 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: 15.0

#761 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: 14.0

#762 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: 15.0

#763 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  account_move_line_stock_info/i18n/it.po
  procurement_auto_create_group/i18n/it.po
  stock_available/i18n/it.po
  stock_available_mrp/i18n/it.po
  stock_available_unreserved/i18n/it.po
  stock_change_qty_reason/i18n/it.po
  stock_cycle_count/i18n/it.po
  stock_inventory_exclude_sublocation/i18n/it.po
  stock_inventory_preparation_filter/i18n/it.po
  stock_mts_mto_rule/i18n/it.po
  stock_orderpoint_uom/i18n/it.po
  stock_quant_manual_assign/i18n/it.po
  stock_warehouse_calendar/i18n/it.po
Labels: 14.0

#764 [MIG] stock_putaway_method in v15
  stock_putaway_method/README.rst
  stock_putaway_method/__init__.py
  stock_putaway_method/__manifest__.py
  stock_putaway_method/i18n/cs_CZ.po
  stock_putaway_method/i18n/fr.po
  stock_putaway_method/i18n/stock_putaway_method.pot
  stock_putaway_method/models/__init__.py
  stock_putaway_method/models/product_strategy.py
  stock_putaway_method/readme/CONTRIBUTORS.rst
  stock_putaway_method/readme/DESCRIPTION.rst
  stock_putaway_method/readme/USAGE.rst
  stock_putaway_method/static/description/icon.png
  stock_putaway_method/static/description/index.html
  stock_putaway_method/tests/__init__.py
  stock_putaway_method/tests/test_putaway_method.py
  stock_putaway_method/views/product_strategy_views.xml
Labels: 15.0.project_la_443

#765 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: 13.0.project_mi_465

#766 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_show_linked/odoo/addons/stock_picking_show_linked
  setup/stock_picking_show_linked/setup.py
  stock_change_qty_reason/i18n/ar.po
  stock_change_qty_reason/i18n/bs.po
  stock_change_qty_reason/i18n/ca.po
  stock_change_qty_reason/i18n/cs.po
  stock_change_qty_reason/i18n/cs_CZ.po
  stock_change_qty_reason/i18n/de.po
  stock_change_qty_reason/i18n/en_GB.po
  stock_change_qty_reason/i18n/es.po
  stock_change_qty_reason/i18n/es_CR.po
  stock_change_qty_reason/i18n/es_EC.po
  stock_change_qty_reason/i18n/es_MX.po
  stock_change_qty_reason/i18n/es_VE.po
  stock_change_qty_reason/i18n/et.po
  stock_change_qty_reason/i18n/fi.po
  stock_change_qty_reason/i18n/fr.po
  stock_change_qty_reason/i18n/hr.po
  stock_change_qty_reason/i18n/hu.po
  stock_change_qty_reason/i18n/it.po
  stock_change_qty_reason/i18n/ja.po
  stock_change_qty_reason/i18n/lt.po
  stock_change_qty_reason/i18n/mk.po
  stock_change_qty_reason/i18n/mn.po
  stock_change_qty_reason/i18n/nb.po
  stock_change_qty_reason/i18n/nl.po
  stock_change_qty_reason/i18n/nl_BE.po
  stock_change_qty_reason/i18n/nl_NL.po
  stock_change_qty_reason/i18n/pl.po
  stock_change_qty_reason/i18n/pt.po
  stock_change_qty_reason/i18n/pt_BR.po
  stock_change_qty_reason/i18n/pt_PT.po
  stock_change_qty_reason/i18n/ro.po
  stock_change_qty_reason/i18n/ru.po
  stock_change_qty_reason/i18n/sl.po
  stock_change_qty_reason/i18n/sr@latin.po
  stock_change_qty_reason/i18n/sv.po
  stock_change_qty_reason/i18n/th.po
  stock_change_qty_reason/i18n/tr.po
  stock_change_qty_reason/i18n/tr_TR.po
  stock_change_qty_reason/i18n/vi.po
  stock_change_qty_reason/i18n/zh_CN.po
  stock_change_qty_reason/i18n/zh_TW.po
  stock_picking_show_linked/README.rst
  stock_picking_show_linked/__init__.py
  stock_picking_show_linked/__manifest__.py
  stock_picking_show_linked/i18n/stock_picking_show_linked.pot
  stock_picking_show_linked/models/__init__.py
  stock_picking_show_linked/models/stock_picking.py
  stock_picking_show_linked/readme/CONTRIBUTORS.rst
  stock_picking_show_linked/readme/DESCRIPTION.rst
  stock_picking_show_linked/static/description/icon.png
  stock_picking_show_linked/static/description/index.html
  stock_picking_show_linked/views/stock_picking.xml
Labels: 13.0

#767 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  account_move_line_product/README.rst
  account_move_line_product/__init__.py
  account_move_line_product/__manifest__.py
  account_move_line_product/i18n/account_move_line_product.pot
  account_move_line_product/i18n/ca.po
  account_move_line_product/i18n/cs_CZ.po
  account_move_line_product/i18n/de.po
  account_move_line_product/i18n/el_GR.po
  account_move_line_product/i18n/es.po
  account_move_line_product/i18n/es_ES.po
  account_move_line_product/i18n/eu.po
  account_move_line_product/i18n/fi.po
  account_move_line_product/i18n/fr.po
  account_move_line_product/i18n/fr_CH.po
  account_move_line_product/i18n/fr_FR.po
  account_move_line_product/i18n/gl.po
  account_move_line_product/i18n/hr.po
  account_move_line_product/i18n/hr_HR.po
  account_move_line_product/i18n/it.po
  account_move_line_product/i18n/nl.po
  account_move_line_product/i18n/nl_NL.po
  account_move_line_product/i18n/pt.po
  account_move_line_product/i18n/pt_BR.po
  account_move_line_product/i18n/ro.po
  account_move_line_product/i18n/ru.po
  account_move_line_product/i18n/sl.po
  account_move_line_product/i18n/tr.po
  account_move_line_product/i18n/tr_TR.po
  account_move_line_product/i18n/vi_VN.po
  account_move_line_product/i18n/zh_CN.po
  account_move_line_product/readme/CONTRIBUTORS.rst
  account_move_line_product/readme/DESCRIPTION.rst
  account_move_line_product/static/description/icon.png
  account_move_line_product/static/description/index.html
  account_move_line_product/views/account_move_line_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_product/odoo/addons/account_move_line_product
  setup/account_move_line_product/setup.py
Labels: 15.0
