Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2022-08, with the labels that each got.

#768 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_location_route_description/odoo/addons/stock_location_route_description
  setup/stock_location_route_description/setup.py
  stock_location_route_description/README.rst
  stock_location_route_description/__init__.py
  stock_location_route_description/__manifest__.py
  stock_location_route_description/i18n/stock_location_route_description.pot
  stock_location_route_description/models/__init__.py
  stock_location_route_description/models/stock_location_route.py
  stock_location_route_description/readme/CONTRIBUTORS.rst
  stock_location_route_description/readme/DESCRIPTION.rst
  stock_location_route_description/static/description/icon.png
  stock_location_route_description/static/description/index.html
  stock_location_route_description/tests/__init__.py
  stock_location_route_description/tests/test_stock_location_route_description.py
  stock_location_route_description/views/stock_location_route_views.xml
Labels: 13.0

#771 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_inventory_chatter/i18n/nb_NO.po
  stock_inventory_exclude_sublocation/i18n/nb_NO.po
  stock_move_location/i18n/nb_NO.po
Labels: 13.0

#772 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  stock_location_route_description/__manifest__.py
  stock_location_route_description/models/stock_location_route.py
  stock_location_route_description/tests/test_stock_location_route_description.py
Labels: 13.0

#773 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  stock_inventory_chatter/i18n/nb_NO.po
  stock_inventory_exclude_sublocation/i18n/nb_NO.po
  stock_location_route_description/__manifest__.py
  stock_location_route_description/models/stock_location_route.py
  stock_location_route_description/tests/test_stock_location_route_description.py
  stock_move_location/i18n/nb_NO.po
Labels: 13.0.project_mi_465

#774 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  account_move_line_stock_info/i18n/ca.po
  procurement_auto_create_group/i18n/ca.po
  stock_available/i18n/ca.po
  stock_available_mrp/i18n/ca.po
  stock_available_unreserved/i18n/ca.po
  stock_warehouse_calendar/i18n/ca.po
Labels: 15.0

#775 Backmerging 15.0 into 15.0.project_MI_465
  account_move_line_stock_info/i18n/ca.po
  procurement_auto_create_group/i18n/ca.po
  stock_available/i18n/ca.po
  stock_available_mrp/i18n/ca.po
  stock_available_unreserved/i18n/ca.po
  stock_warehouse_calendar/i18n/ca.po
Labels: 15.0.project_mi_465
