Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2022-04, with the labels that each got.

#723 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_move_location/__manifest__.py
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: 13.0

#724 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0

#725 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_orderpoint_route/odoo/addons/stock_orderpoint_route
  setup/stock_orderpoint_route/setup.py
  stock_orderpoint_route/README.rst
  stock_orderpoint_route/__init__.py
  stock_orderpoint_route/__manifest__.py
  stock_orderpoint_route/i18n/stock_orderpoint_route.pot
  stock_orderpoint_route/models/__init__.py
  stock_orderpoint_route/models/stock_warehouse_orderpoint.py
  stock_orderpoint_route/readme/CONTRIBUTORS.rst
  stock_orderpoint_route/readme/DESCRIPTION.rst
  stock_orderpoint_route/readme/USAGE.rst
  stock_orderpoint_route/static/description/icon.png
  stock_orderpoint_route/static/description/index.html
  stock_orderpoint_route/tests/__init__.py
  stock_orderpoint_route/tests/test_stock_orderpoint_route.py
  stock_orderpoint_route/views/stock_warehouse_orderpoint_views.xml
Labels: 12.0

#726 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_available_mrp/README.rst
  stock_available_mrp/__manifest__.py
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/mrp_bom.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/readme/USAGE.rst
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/test_potential_qty.py
  stock_available_mrp/views/mrp_bom_views.xml
Labels: 13.0

#727 Updating from latest OCA 13.0
  stock_available_mrp/README.rst
  stock_available_mrp/__manifest__.py
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/mrp_bom.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/readme/USAGE.rst
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/test_potential_qty.py
  stock_available_mrp/views/mrp_bom_views.xml
  stock_move_location/__manifest__.py
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
  stock_quant_manual_assign/i18n/ca.po
  stock_quant_manual_assign/i18n/es.po
Labels: 13.0.project_mi_465

#728 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_orderpoint_manual_procurement/__manifest__.py
  stock_orderpoint_manual_procurement/models/stock_warehouse_orderpoint.py
Labels: 14.0

#729 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/models/product.py
  stock_request_tier_validation/i18n/es.po
  stock_request_tier_validation/i18n/stock_request_tier_validation.pot
  stock_request_tier_validation/i18n/zh_CN.po
Labels: 14.0

#731 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_exception/odoo/addons/stock_exception
  setup/stock_exception/setup.py
  stock_exception/README.rst
  stock_exception/__init__.py
  stock_exception/__manifest__.py
  stock_exception/data/stock_exception_data.xml
  stock_exception/i18n/stock_exception.pot
  stock_exception/models/__init__.py
  stock_exception/models/exception_rule.py
  stock_exception/models/stock.py
  stock_exception/models/stock_move.py
  stock_exception/readme/CONTRIBUTORS.rst
  stock_exception/readme/DESCRIPTION.rst
  stock_exception/security/ir.model.access.csv
  stock_exception/static/description/icon.png
  stock_exception/static/description/index.html
  stock_exception/views/stock_view.xml
  stock_exception/wizard/__init__.py
  stock_exception/wizard/stock_exception_confirm.py
  stock_exception/wizard/stock_exception_confirm_view.xml
Labels: 14.0
