Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2022-01, with the labels that each got.

#681 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_inventory_preparation_filter/i18n/sk.po
Labels: 14.0

#683 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_move_location/odoo/addons/stock_move_location
  setup/stock_move_location/setup.py
  stock_move_location/README.rst
  stock_move_location/__init__.py
  stock_move_location/__manifest__.py
  stock_move_location/data/stock_quant_view.xml
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/fr.po
  stock_move_location/i18n/fr_BE.po
  stock_move_location/i18n/fr_FR.po
  stock_move_location/i18n/ja.po
  stock_move_location/i18n/ja_JP.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/init_hook.py
  stock_move_location/models/__init__.py
  stock_move_location/models/stock_move.py
  stock_move_location/models/stock_picking.py
  stock_move_location/models/stock_picking_type.py
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/readme/DESCRIPTION.rst
  stock_move_location/readme/ROADMAP.rst
  stock_move_location/readme/USAGE.rst
  stock_move_location/security/ir.model.access.csv
  stock_move_location/static/description/icon.png
  stock_move_location/static/description/index.html
  stock_move_location/tests/__init__.py
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/tests/test_stock_fillwithstock.py
  stock_move_location/views/stock_picking.xml
  stock_move_location/views/stock_picking_type_views.xml
  stock_move_location/wizard/__init__.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: 15.0

#684 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_request_purchase/odoo/addons/stock_request_purchase
  setup/stock_request_purchase/setup.py
  stock_request_purchase/README.rst
  stock_request_purchase/__init__.py
  stock_request_purchase/__manifest__.py
  stock_request_purchase/i18n/de.po
  stock_request_purchase/i18n/es.po
  stock_request_purchase/i18n/stock_request_purchase.pot
  stock_request_purchase/i18n/zh_CN.po
  stock_request_purchase/models/__init__.py
  stock_request_purchase/models/purchase_order.py
  stock_request_purchase/models/purchase_order_line.py
  stock_request_purchase/models/stock_request.py
  stock_request_purchase/models/stock_request_order.py
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/readme/CONTRIBUTORS.rst
  stock_request_purchase/readme/DESCRIPTION.rst
  stock_request_purchase/readme/ROADMAP.rst
  stock_request_purchase/readme/USAGE.rst
  stock_request_purchase/security/ir.model.access.csv
  stock_request_purchase/static/description/icon.png
  stock_request_purchase/static/description/index.html
  stock_request_purchase/tests/__init__.py
  stock_request_purchase/tests/test_stock_request_purchase.py
  stock_request_purchase/views/purchase_order_views.xml
  stock_request_purchase/views/stock_request_order_views.xml
  stock_request_purchase/views/stock_request_views.xml
Labels: 14.0

#686 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_secondary_unit/odoo/addons/stock_secondary_unit
  setup/stock_secondary_unit/setup.py
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/i18n/zh_CN.po
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/readme/DESCRIPTION.rst
  stock_secondary_unit/readme/USAGE.rst
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: 14.0

#688 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  product_quantity_update_force_inventory/README.rst
  product_quantity_update_force_inventory/__init__.py
  product_quantity_update_force_inventory/__manifest__.py
  product_quantity_update_force_inventory/i18n/product_quantity_update_force_inventory.pot
  product_quantity_update_force_inventory/models/__init__.py
  product_quantity_update_force_inventory/models/product.py
  product_quantity_update_force_inventory/models/stock_quant.py
  product_quantity_update_force_inventory/readme/CONTRIBUTORS.rst
  product_quantity_update_force_inventory/readme/DESCRIPTION.rst
  product_quantity_update_force_inventory/static/description/icon.png
  product_quantity_update_force_inventory/static/description/index.html
  product_quantity_update_force_inventory/tests/__init__.py
  product_quantity_update_force_inventory/tests/test_stock_quant_editable_view_block.py
  product_quantity_update_force_inventory/views/product_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_quantity_update_force_inventory/odoo/addons/product_quantity_update_force_inventory
  setup/product_quantity_update_force_inventory/setup.py
  stock_orderpoint_uom/tests/test_stock_orderpoint_procure_uom.py
Labels: 14.0

#689 Merging 13.0 into 13.0.project_MI_465
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_package_grouped/odoo/addons/stock_picking_package_grouped
  setup/stock_picking_package_grouped/setup.py
  stock_picking_package_grouped/README.rst
  stock_picking_package_grouped/__init__.py
  stock_picking_package_grouped/__manifest__.py
  stock_picking_package_grouped/i18n/es.po
  stock_picking_package_grouped/i18n/stock_picking_package_grouped.pot
  stock_picking_package_grouped/models/__init__.py
  stock_picking_package_grouped/models/stock_picking.py
  stock_picking_package_grouped/models/stock_picking_type.py
  stock_picking_package_grouped/readme/CONFIGURE.rst
  stock_picking_package_grouped/readme/CONTRIBUTORS.rst
  stock_picking_package_grouped/readme/DESCRIPTION.rst
  stock_picking_package_grouped/readme/USAGE.rst
  stock_picking_package_grouped/static/description/icon.png
  stock_picking_package_grouped/static/description/index.html
  stock_picking_package_grouped/tests/__init__.py
  stock_picking_package_grouped/tests/test_stock_picking_package_grouped.py
  stock_picking_package_grouped/views/stock_picking_type_views.xml
Labels: 13.0.project_mi_465

#690 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_orderpoint_move_link/odoo/addons/stock_orderpoint_move_link
  setup/stock_orderpoint_move_link/setup.py
  stock_orderpoint_move_link/README.rst
  stock_orderpoint_move_link/__init__.py
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_move_link/i18n/stock_orderpoint_move_link.pot
  stock_orderpoint_move_link/i18n/zh_CN.po
  stock_orderpoint_move_link/models/__init__.py
  stock_orderpoint_move_link/models/stock.py
  stock_orderpoint_move_link/models/stock_move.py
  stock_orderpoint_move_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_move_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_move_link/readme/DESCRIPTION.rst
  stock_orderpoint_move_link/static/description/icon.png
  stock_orderpoint_move_link/static/description/index.html
  stock_orderpoint_move_link/tests/__init__.py
  stock_orderpoint_move_link/tests/test_stock_orderpoint_move_link.py
  stock_orderpoint_move_link/views/stock_move_views.xml
Labels: 15.0

#691 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_reserve_rule/README.rst
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/static/description/index.html
Labels: 14.0

#693 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_available/odoo/addons/stock_available
  setup/stock_available/setup.py
  stock_available/README.rst
  stock_available/__init__.py
  stock_available/__manifest__.py
  stock_available/i18n/ar.po
  stock_available/i18n/ca.po
  stock_available/i18n/cs_CZ.po
  stock_available/i18n/de.po
  stock_available/i18n/el_GR.po
  stock_available/i18n/es.po
  stock_available/i18n/es_ES.po
  stock_available/i18n/es_MX.po
  stock_available/i18n/eu.po
  stock_available/i18n/fi.po
  stock_available/i18n/fr.po
  stock_available/i18n/fr_CH.po
  stock_available/i18n/fr_FR.po
  stock_available/i18n/gl.po
  stock_available/i18n/hr.po
  stock_available/i18n/hr_HR.po
  stock_available/i18n/it.po
  stock_available/i18n/nl.po
  stock_available/i18n/nl_NL.po
  stock_available/i18n/pt.po
  stock_available/i18n/pt_BR.po
  stock_available/i18n/ro.po
  stock_available/i18n/ru.po
  stock_available/i18n/sl.po
  stock_available/i18n/stock_available.pot
  stock_available/i18n/tr.po
  stock_available/i18n/tr_TR.po
  stock_available/i18n/vi_VN.po
  stock_available/i18n/zh_CN.po
  stock_available/models/__init__.py
  stock_available/models/product_product.py
  stock_available/models/product_template.py
  stock_available/models/res_config_settings.py
  stock_available/readme/CONFIGURE.rst
  stock_available/readme/CONTRIBUTORS.rst
  stock_available/readme/DESCRIPTION.rst
  stock_available/readme/USAGE.rst
  stock_available/static/description/icon.png
  stock_available/static/description/index.html
  stock_available/tests/__init__.py
  stock_available/tests/test_stock_available.py
  stock_available/views/product_product_view.xml
  stock_available/views/product_template_view.xml
  stock_available/views/res_config_settings_views.xml
Labels: 15.0

#694 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_putaway_product_template/__manifest__.py
  stock_putaway_product_template/views/stock_putaway_rule_views.xml
Labels: 13.0

#697 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_request/i18n/fr.po
Labels: 14.0
