Repository brain-tec/stock-logistics-warehouse, pull requests merged in 2023-06, with the labels that each got.

#1060 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_quant_manual_assign/i18n/es.po
Labels: 12.0

#1061 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  stock_request/__manifest__.py
  stock_request/models/stock_move.py
Labels: 15.0

#1062 Syncing from upstream OCA/stock-logistics-warehouse (8.0)
  stock_inventory_revaluation/i18n/it.po
Labels: 8.0

#1064 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  stock_inventory_revaluation/i18n/it.po
Labels: 10.0

#1065 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_inventory_revaluation/i18n/it.po
Labels: 12.0

#1066 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/models/stock_move.py
  account_move_line_stock_info/tests/test_account_move_line_stock_move.py
  account_move_line_stock_info/views/account_move_line_view.xml
Labels: 13.0

#1067 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/models/stock_move.py
  account_move_line_stock_info/views/account_move_line_view.xml
Labels: 14.0

#1068 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/models/stock_move.py
  account_move_line_stock_info/views/account_move_line_view.xml
  stock_move_location/README.rst
  stock_move_location/__manifest__.py
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/fr.po
  stock_move_location/i18n/fr_BE.po
  stock_move_location/i18n/fr_FR.po
  stock_move_location/i18n/ja.po
  stock_move_location/i18n/ja_JP.po
  stock_move_location/i18n/sk.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/static/description/index.html
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: 15.0

#1069 Syncing from upstream OCA/stock-logistics-warehouse (16.0)
  README.md
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/models/stock_move.py
  account_move_line_stock_info/views/account_move_line_view.xml
Labels: 16.0

#1070 Syncing from upstream OCA/stock-logistics-warehouse (8.0)
  stock_cycle_count/i18n/it.po
  stock_putaway_product/i18n/it.po
  stock_valuation_account_manual_adjustment/i18n/it.po
Labels: 8.0

#1071 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_cycle_count/i18n/it.po
  stock_demand_estimate/i18n/it.po
  stock_inventory_verification_request/i18n/it.po
  stock_orderpoint_manual_procurement/i18n/it.po
  stock_putaway_product/i18n/it.po
  stock_quant_manual_assign/i18n/it.po
  stock_valuation_account_manual_adjustment/i18n/it.po
Labels: 9.0

#1072 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  stock_demand_estimate/i18n/it.po
Labels: 10.0

#1073 Syncing from upstream OCA/stock-logistics-warehouse (16.0)
  stock_quant_manual_assign/i18n/it.po
Labels: 16.0

#1074 Syncing from upstream OCA/stock-logistics-warehouse (8.0)
  stock_cycle_count/i18n/it.po
  stock_putaway_product/i18n/it.po
  stock_valuation_account_manual_adjustment/i18n/it.po
Labels: 8.0

#1075 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_cycle_count/i18n/it.po
  stock_demand_estimate/i18n/it.po
  stock_inventory_verification_request/i18n/it.po
  stock_orderpoint_manual_procurement/i18n/it.po
  stock_quant_manual_assign/i18n/it.po
  stock_reserve/i18n/it.po
Labels: 9.0

#1076 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  stock_cycle_count/i18n/it.po
  stock_demand_estimate/i18n/it.po
  stock_inventory_verification_request/i18n/it.po
  stock_quant_manual_assign/i18n/it.po
  stock_valuation_account_manual_adjustment/i18n/it.po
Labels: 10.0

#1077 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_cycle_count/i18n/it.po
  stock_demand_estimate/i18n/it.po
  stock_inventory_verification_request/i18n/it.po
  stock_putaway_product/i18n/it.po
  stock_quant_manual_assign/i18n/it.po
Labels: 11.0

#1078 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_cycle_count/i18n/it.po
Labels: 12.0

#1079 Syncing from upstream OCA/stock-logistics-warehouse (8.0)
  stock_reserve/i18n/it.po
Labels: 8.0

#1080 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_reserve/i18n/it.po
Labels: 9.0

#1081 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  stock_reserve/i18n/it.po
Labels: 10.0

#1082 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_reserve/i18n/it.po
Labels: 13.0

#1083 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_reserve/i18n/it.po
Labels: 14.0

#1084 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  stock_reserve/i18n/it.po
Labels: 15.0

#1085 Syncing from upstream OCA/stock-logistics-warehouse (16.0)
  stock_reserve/i18n/it.po
Labels: 16.0

#1086 Syncing from upstream OCA/stock-logistics-warehouse (8.0)
  stock_orderpoint_manual_procurement/i18n/it.po
Labels: 8.0

#1087 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_orderpoint_manual_procurement/i18n/it.po
Labels: 9.0

#1088 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_location_children/i18n/it.po
  stock_location_orderpoint/__manifest__.py
  stock_location_orderpoint/tests/test_location_orderpoint.py
  stock_location_orderpoint_source_relocate/__manifest__.py
  stock_location_orderpoint_source_relocate/tests/test_location_orderpoint.py
Labels: 14.0

#1089 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request/i18n/it.po
Labels: 12.0

#1090 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_request/i18n/it.po
  stock_reserve_rule/i18n/it.po
Labels: 14.0

#1091 Syncing from upstream OCA/stock-logistics-warehouse (8.0)
  business_product_location/i18n/it.po
Labels: 8.0

#1092 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  business_product_location/i18n/it.po
Labels: 10.0

#1093 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_inventory_verification_request/i18n/it.po
Labels: 9.0

#1094 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_request/__manifest__.py
  stock_request/i18n/it.po
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
Labels: 14.0

#1095 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_cycle_count/i18n/it.po
  stock_inventory_chatter/i18n/it.po
  stock_inventory_verification_request/i18n/it.po
Labels: 9.0

#1096 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_cycle_count/i18n/it.po
Labels: 12.0

#1097 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_cycle_count/i18n/it.po
Labels: 13.0

#1098 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_request/i18n/it.po
Labels: 14.0

#1099 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_cycle_count/i18n/it.po
  stock_inventory_chatter/i18n/it.po
  stock_inventory_verification_request/i18n/it.po
Labels: 9.0

#1100 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request/i18n/it.po
Labels: 12.0

#1101 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  stock_request/i18n/it.po
Labels: 14.0

#1102 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/models/stock_quant.py
Labels: 15.0

#1103 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_request_separate_picking/odoo/addons/stock_request_separate_picking
  setup/stock_request_separate_picking/setup.py
  stock_request_separate_picking/README.rst
  stock_request_separate_picking/__init__.py
  stock_request_separate_picking/__manifest__.py
  stock_request_separate_picking/i18n/stock_request_separate_picking.pot
  stock_request_separate_picking/models/__init__.py
  stock_request_separate_picking/models/res_company.py
  stock_request_separate_picking/models/res_config_settings.py
  stock_request_separate_picking/models/stock_request_abstract.py
  stock_request_separate_picking/models/stock_request_order.py
  stock_request_separate_picking/readme/CONFIGURE.rst
  stock_request_separate_picking/readme/CONTRIBUTORS.rst
  stock_request_separate_picking/readme/DESCRIPTION.rst
  stock_request_separate_picking/readme/HISTORY.rst
  stock_request_separate_picking/static/description/icon.png
  stock_request_separate_picking/static/description/index.html
  stock_request_separate_picking/tests/__init__.py
  stock_request_separate_picking/tests/test_stock_request_separate_picking.py
  stock_request_separate_picking/views/res_config_settings_views.xml
Labels: 15.0

#1104 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  stock_free_quantity/i18n/fr.po
Labels: 15.0

#1105 Syncing from upstream OCA/stock-logistics-warehouse (8.0)
  stock_inventory_revaluation/i18n/it.po
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 8.0

#1106 Syncing from upstream OCA/stock-logistics-warehouse (9.0)
  stock_inventory_revaluation/i18n/it.po
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 9.0

#1107 Syncing from upstream OCA/stock-logistics-warehouse (10.0)
  stock_inventory_revaluation/i18n/it.po
  stock_orderpoint_automatic_creation/i18n/it.po
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 10.0

#1108 Syncing from upstream OCA/stock-logistics-warehouse (11.0)
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 11.0

#1109 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_inventory_revaluation/i18n/it.po
  stock_orderpoint_automatic_creation/i18n/it.po
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 12.0

#1110 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  stock_warehouse_orderpoint_stock_info/i18n/it.po
Labels: 13.0

#1111 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  stock_request/README.rst
  stock_request/__manifest__.py
  stock_request/models/stock_request_order.py
  stock_request/readme/CONTRIBUTORS.rst
  stock_request/static/description/index.html
  stock_request/tests/test_stock_request.py
Labels: 13.0

#1113 [16.0][MIG] stock_secondary_unit
  setup/stock_secondary_unit/odoo/addons/stock_secondary_unit
  setup/stock_secondary_unit/setup.py
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/i18n/zh_CN.po
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product_product.py
  stock_secondary_unit/models/product_template.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/models/stock_product_secondary_unit_mixin.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/readme/DESCRIPTION.rst
  stock_secondary_unit/readme/USAGE.rst
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/test-requirements.txt
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: 16.0.project_ba_688

#1114 Syncing from upstream OCA/stock-logistics-warehouse (12.0)
  stock_request/i18n/it.po
Labels: 12.0

#1115 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  stock_warehouse_calendar/i18n/it.po
Labels: 15.0

#1116 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  product_route_profile/i18n/nl.po
Labels: 14.0

#1117 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_picking_volume/__manifest__.py
  stock_picking_volume/models/stock_picking.py
  stock_picking_volume/tests/test_stock_picking_volume.py
Labels: 14.0

#1118 Syncing from upstream OCA/stock-logistics-warehouse (13.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_quant_reservation_info/odoo/addons/stock_quant_reservation_info
  setup/stock_quant_reservation_info/setup.py
  setup/stock_quant_reservation_info_mrp/odoo/addons/stock_quant_reservation_info_mrp
  setup/stock_quant_reservation_info_mrp/setup.py
  stock_quant_reservation_info/README.rst
  stock_quant_reservation_info/__init__.py
  stock_quant_reservation_info/__manifest__.py
  stock_quant_reservation_info/i18n/stock_quant_reservation_info.pot
  stock_quant_reservation_info/models/__init__.py
  stock_quant_reservation_info/models/stock_move_line.py
  stock_quant_reservation_info/models/stock_quant.py
  stock_quant_reservation_info/readme/CONTRIBUTORS.rst
  stock_quant_reservation_info/readme/DESCRIPTION.rst
  stock_quant_reservation_info/readme/USAGE.rst
  stock_quant_reservation_info/static/description/icon.png
  stock_quant_reservation_info/static/description/index.html
  stock_quant_reservation_info/tests/__init__.py
  stock_quant_reservation_info/tests/test_stock_quant_reservation_info.py
  stock_quant_reservation_info/views/stock_move_line.xml
  stock_quant_reservation_info/views/stock_quant.xml
  stock_quant_reservation_info_mrp/README.rst
  stock_quant_reservation_info_mrp/__init__.py
  stock_quant_reservation_info_mrp/__manifest__.py
  stock_quant_reservation_info_mrp/i18n/stock_quant_reservation_info_mrp.pot
  stock_quant_reservation_info_mrp/models/__init__.py
  stock_quant_reservation_info_mrp/models/stock_move_line.py
  stock_quant_reservation_info_mrp/readme/CONTRIBUTORS.rst
  stock_quant_reservation_info_mrp/readme/DESCRIPTION.rst
  stock_quant_reservation_info_mrp/readme/USAGE.rst
  stock_quant_reservation_info_mrp/static/description/icon.png
  stock_quant_reservation_info_mrp/static/description/index.html
  stock_quant_reservation_info_mrp/tests/__init__.py
  stock_quant_reservation_info_mrp/tests/test_stock_quant_reservation_info_mrp.py
  stock_quant_reservation_info_mrp/views/stock_move_line.xml
Labels: 13.0

#1119 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_exception/__manifest__.py
  stock_exception/models/stock.py
Labels: 14.0

#1121 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  stock_reserve/__manifest__.py
  stock_reserve/data/stock_data.xml
Labels: 14.0

#1122 Syncing from upstream OCA/stock-logistics-warehouse (15.0)
  README.md
  stock_reserve/__manifest__.py
  stock_reserve/data/stock_data.xml
Labels: 15.0

#1123 Syncing from upstream OCA/stock-logistics-warehouse (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_volume_packaging/odoo/addons/stock_picking_volume_packaging
  setup/stock_picking_volume_packaging/setup.py
  stock_inventory_line_open/i18n/fr.po
  stock_picking_volume_packaging/README.rst
  stock_picking_volume_packaging/__init__.py
  stock_picking_volume_packaging/__manifest__.py
  stock_picking_volume_packaging/i18n/stock_picking_volume_packaging.pot
  stock_picking_volume_packaging/models/__init__.py
  stock_picking_volume_packaging/models/stock_move.py
  stock_picking_volume_packaging/readme/CONTRIBUTORS.rst
  stock_picking_volume_packaging/readme/CREDITS.rst
  stock_picking_volume_packaging/readme/DESCRIPTION.rst
  stock_picking_volume_packaging/readme/USAGE.rst
  stock_picking_volume_packaging/static/description/icon.png
  stock_picking_volume_packaging/static/description/index.html
  stock_picking_volume_packaging/tests/__init__.py
  stock_picking_volume_packaging/tests/test_stock_move_volume.py
Labels: 14.0

#1124 Syncing from upstream OCA/stock-logistics-warehouse (16.0)
  README.md
  stock_reserve/__manifest__.py
  stock_reserve/data/stock_data.xml
Labels: 16.0
